### ISSUE TITLE
Logging from developer.log properties to devtools

### ISSUE THREAD

**Issue by workerbee22** [flutter/devtools#1108]
In Flutter when using dart:developer v2.5.0 for logging, only the log message and the 'name' property values are displayed. For example:

![image](https://user-images.githubusercontent.com/5154664/65959162-a3729900-e494-11e9-873f-7353081d495e.png)

When using other available properties of developer.log, they do not appear in DevTools. For example other properties that could appear in DevTools UI:

```
developer.log(
    logMessage,
    level: level,
    sequenceNumber: currentSequenceNum,
    zone: Zone.current,
    error: objectDetails,
    time: DateTime.now(),
    name: appNamePrefix + logSource,
    stackTrace: logStackTrace,
  );
```

**Comment by devoncarew** [comment]
That presentation line is more of a summary than the full details of the event. You should be able to click on the line and see the details in a larger area.

**Comment by terrylucas** [comment]
@pq 

These are how the log parameters are displayed (or not).  Should the sequenceNumber, zone and time be displayed somewhere?  Should logging level be displayed (other than highlight color) either as integer or as Level e.g, e.g., SHOUT, INFO, FINE, FINEST, WARNING, etc

Values that are displayed in log view:
- logMessage appears in right pane under Message column and appears as first line 
- Level (SHOUT value of 1200) will display the kind with red highlight otherwise black highlight for Kind.
- name appears Kind column left-most pane.
- stackTrace appears in expanded view in right-most pane.
- error is displayed in the right-most pane e.g.,
`RangeError: Invalid value: Not in range 0..200, inclusive: 100`

Things that are not displayed in log view:
- sequenceNumber doesn't appear
- zone doesn't appear
- time doesn't appear (other than the timestamp of when log was called)

**Comment by workerbee22** [comment]
Thought I'd better provide more detail on this issue. 

Android Studio (stable):

![image](https://user-images.githubusercontent.com/5154664/66433949-326f4a80-ea6d-11e9-8196-8d73bcd5940f.png)

With Dart and Flutter Plugins:

![image](https://user-images.githubusercontent.com/5154664/66434391-2c2d9e00-ea6e-11e9-80f2-565a966e0206.png)

Flutter doctor output for Flutter 1.9.1 Hotfix 4:

![image](https://user-images.githubusercontent.com/5154664/66433831-ea502800-ea6c-11e9-802b-fcb3a06db23c.png)

DevTools version:

![image](https://user-images.githubusercontent.com/5154664/66435182-fa1d3b80-ea6f-11e9-9f32-d5484eb289d9.png)

If I create just a standard Flutter project with the default Flutter app, then just add a test call for logging as follows:

```
  developer.log(
    "Test message 1",
    level: 100,
    sequenceNumber: 1,
    zone: Zone.current,
    error: "testObject",
    time: DateTime.now(),
    name: "sourceOfLogMessage",
  );
```

I see only this in DevTools ie. the message and the error object:

![image](https://user-images.githubusercontent.com/5154664/66435351-5e3fff80-ea70-11e9-8213-ad897759373a.png)

- **Level** I had not tried at 1200. Documentation suggestion ie. what level ranges result in what colors in DevTools?
- **Zone** does not appear anywhere
- **Time** does not appear, but perhaps because it is in the Summary that is probably fine

**Comment by workerbee22** [comment]
The other part of this issue is a 'timing' issue with output to the Console in Android Studio. Run any Flutter app with logging and there is no logging outputted to the Console in AS for some time. For example, if I make 3 calls to log messages, when app is first run in Debug, the first 2 messages do not get outputted to Console. I only get the 3rd message:

![image](https://user-images.githubusercontent.com/5154664/66435855-7f552000-ea71-11e9-9467-dd9738bbac97.png)

If I then do a Hot Restart (not a Hot Reload) I do see all 3 logging messages outputted to AS Console output:

![image](https://user-images.githubusercontent.com/5154664/66435987-b88d9000-ea71-11e9-96d1-6e1950c2065a.png)

This is very annoying, because all logging early in the app is not outputted to console.
