### ISSUE TITLE
[fuchsia] Unable to see timeline/debug in devtools for Fuchsia applications

### ISSUE THREAD

**Issue by iskakaushik** [flutter/devtools#1225]
## Repro Steps

1. go/build-fuchsia to get a fuchsia device up and running.
2. Make sure to build it with `tiles` and `spinning_cube` as part of the build. `fx set workstation.chromebook-x64 --with //topaz/app/spinning_cube:spinning_cube --with-base //garnet/packages:default --with-base //bundles:tools --with-base //garnet/packages/prod:sbase`
3. `fx shell -- tiles_ctl start` to start the tiles server, you should see a white screen.
4. `fx shell -- tiles_ctl add fuchsia-pkg://fuchsia.com/spinning_cube#meta/spinning_cube.cmx` should start the spinning cube app.
5. `fx syslog > /tmp/temp_log_file.txt`, search the temp log file for "Observatory" port.
7. `fx ssh -L 8888:localhost:$DEVICE_OBSERVATORY_PORT root@$(fx get-device-addr)`, this should make observatory be accessible from localhost:8888, you can then connect devtools via this port.

Time line throws the following error to the console:

```
Unchecked runtime.lastError: The message port closed before a response was received.
```

Happy to provide any other pointers as needed.

**Comment by zanderso** [comment]
A few things that I think we've already touched on offline:

"fx" is not available outside of the Fuchsia tree. We should come up with a solution for Fuchsia that relies only on the Fuchsia SDK and engine prebuilts.

To what extent can devtools reuse the flow that's already implemented in the flutter tool? (It's a bit broken right now following the flutter_runner migration to the engine repo, but should be straightforward to stand up again.)

As for (5), the correct way to get the Observatory port on Fuchsia is to read it out of the 'Hub', and not scrape it from the logs. This is because there may be more than one Flutter app running at a time, and therefore more than one log line with "Observatory".

**Comment by jacob314** [comment]
Fyi @kenzieschmoll

**Comment by kenzieschmoll** [comment]
I suspect that the `--trace-systrace` flag is enabled for Fuchsia. Trace events will be forwarded to native logging if this is enabled. We recently ran into this issue in our DevTools app because we were passing this flag to our MacOs build config (see [issue](https://github.com/dart-lang/sdk/issues/40496) for context).

**Comment by iskakaushik** [comment]
I think we can close this issue. Only `flutter_runner` in profile mode redirects traces to dart observatory. All other modes only send them to systrace. So it is working as intended.

Although ideally we can have a flag that will route traces to both systrace and observatory.
