### ISSUE TITLE
Enable profiler for DevTools flutter app

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1410]
Trying to profile DevTools running on Flutter Desktop - getting this error when opening observatory profiler:

![Screen Shot 2019-11-27 at 11 32 53 AM](https://user-images.githubusercontent.com/43759233/69754042-cb375380-1109-11ea-8f0c-8e884fa74ed9.png)

**Comment by kenzieschmoll** [comment]
@bkonyi do you know what could be going on here?

**Comment by bkonyi** [comment]
The exception here should be fixed by #1427. However, profiling still isn't working as `SIGPROF` is being blocked due to the fact that the desktop Flutter application is being launched through flutter_tools which is a Dart process.

When `Process.spawnUri` is called we disable the signals so we're not interrupted when performing a bunch of system calls, but that means that the newly spawned process inherits these disabled signals. Typically we try to reset the signals in the newly spawned process (for new Dart instances) but we can't do it on OSX since there's a small chance an unintended thread will have the signal unblocked and SIGPROF terminates the application if there's no handler setup. It sounds like there's something fundamentally wrong in the OSX kernel that isn't easy to work around.

I think we might have fix for this in https://dart-review.googlesource.com/c/sdk/+/127451/1, but we'll have to see if it causes any issues in the long run.
