### ISSUE TITLE
DevTools Debugger not available after launching Layout Explorer

### ISSUE THREAD

**Issue by raison00** [flutter/devtools#1590]
Once a User selects the Layout Explorer Icon in DevTools, the DevTools top Menu bar and options change, limiting options and removing the Debugger from the Menu.  

When the Layout Explorer has NOT been engaged, the top toolbar looks like:
![image](https://user-images.githubusercontent.com/8105802/73498299-c2fdcd80-4371-11ea-9e41-182a058a560e.png)

When the Layout Explorer HAS been engaged, the top toolbar looks like this:
![image](https://user-images.githubusercontent.com/8105802/73498235-92b62f00-4371-11ea-9ad7-29fe35e3cf0c.png)

If the user closes the Layout Explorer, the top toolbar remains with this view where the icons are more prominent than in the original launch and some options removed.  User no longer has options to access the Debugger in DevTools without a Hot Restart.
![image](https://user-images.githubusercontent.com/8105802/73498235-92b62f00-4371-11ea-9ad7-29fe35e3cf0c.png)

currently using:
![image](https://user-images.githubusercontent.com/8105802/73498519-67800f80-4372-11ea-9f99-f131a1b2c7f5.png)

**Comment by kenzieschmoll** [comment]
The first toolbar screenshot above is the toolbar for the stable version of DevTools (written in dart:html).

The second two screenshots are the toolbar for the alpha version of DevTools (written in Flutter). The "beaker" icon in the upper right allows you to test out the alpha version of DevTools. This is why the appearance changed and allowed you to try new features (like the Layout Explorer). 

The Debugger has been intentionally left out of the alpha version of DevTools due to some limitations. @DaveShuckerow @jacob314 When will we be able to add the debugger to the Flutter version of DevTools?

In order to return to the stable version of DevTools, you can remove "flutter.html#/" from the URL.

**Comment by jacob314** [comment]
The issue is canvaskit support for plugins. The debugger was briefly working with the canvaskit version and then something broken in the canvaskit plugin support. @DaveShuckerow is there a flutter framework bug we can track for that?

**Comment by DaveShuckerow** [comment]
Unassigning myself on account of job change.

**Comment by devoncarew** [comment]
This is addressed with the port to flutter web.
