### ISSUE TITLE
Not all logs are displayed by DevTools

### ISSUE THREAD

**Issue by AAverin** [flutter/devtools#1653]
Looks like logs that happened before DevTools were connected are never displayed in DevTools.

This makes it impossible to see logs and errors that happen during application startup and init phase, including errors when initialising redux store, for example.

**Comment by devoncarew** [comment]
cc @bkonyi, @jacob314 

We could do something here like have a ring buffer in the VM for recent logging events. When a client connects, it could be sent the recent events after it subscribes to log events.

**Comment by jacob314** [comment]
+100 to a ring buffer of past VM Service postEvent and log messages.
If there are performance concerns about dispatching all old events when a client connects, I am also fine with providing a separate API to request all historic events in the ring buffer or all historic events for a specific time range just as you can request all historic timeline events for a time range. 

Chrome devtools supports something similar as you can see log messages from before you open Chrome devtools although those log events sometimes have less structure than log events sent while chrome devtools was open (for example, log events are often just strings instead of having structure).

**Comment by AAverin** [comment]
I don't yet know all the internal details of flutter, but on Android you can probably just read Logcat - all the buffering there is already done.
Not sure about iOS, though.

**Comment by jacob314** [comment]
As long as we only care about this for flutter and not for dart vm apps, we could add the ring buffer tracking to flutter_tools rather than the VM. That would be similar to your suggestion of reading the data from logcat without having to take a dependency on a specific platform implementation.

**Comment by jacob314** [comment]
If getting all the historical data takes only a couple hundred ms then I agree we should just send all the historic data on connection.

**Comment by kenzieschmoll** [comment]
Any updates on this @bkonyi ?

**Comment by bkonyi** [comment]
This is functionality that will eventually live in DDS, so it's probably a month out at the very least.

**Comment by bkonyi** [comment]
DDS support for log history will land in [this CL](https://dart-review.googlesource.com/c/sdk/+/146444). However, this functionality won't be available to use until I've finished integrating DDS with dartdev and flutter_tools.

**Comment by bkonyi** [comment]
DDS support for the standalone VM and non-web Flutter workflows has landed so log history should be sent over the `Logging` stream upon subscription. Web support will hopefully land next week (see https://github.com/flutter/flutter/issues/61259).
