### ISSUE TITLE
Pull survey data from flutter website metadata file.

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1672]
Matching intelliJ issue: https://github.com/flutter/flutter-intellij/issues/4398

We would need to either append to this metadata file (https://github.com/flutter/website/blob/master/src/f/flutter-survey-metadata.json) or create a new one `devtools-survey-metadata`.

This will eliminate the quarterly maintenance burden of managing survey prep ourselves.

**Comment by DanTup** [comment]
Fixed by https://github.com/flutter/devtools/pull/2442?

(note: the survey JSON is currently a 404 due to a change on the website - it works if you use docs.flutter.dev instead of flutter .dev.. I'm waiting to hear from @jayoung-lee to see if we need to update the URLs or if it will end up back at the original URL).

**Comment by jayoung-lee** [comment]
Since all the files that used to be under `flutter.dev/docs` are now under `docs.flutter.dev` after the website update, I think we should update all the paths in the IDE plugins too.

I've asked the VGV team to make a copy of the current json file at `https://flutter.dev/f/flutter-survey-metadata.json` to `https://docs.flutter.dev/f/flutter-survey-metadata.json` so that the survey prompts can work for Q4 2021, but going forward, we'll need to use the new path under `docs.flutter.dev`

**Comment by kenzieschmoll** [comment]
cc @stevemessick - the url in the IntelliJ plugin will need to be updated too
