### ISSUE TITLE
Timeline page broken in dart:html version of the app.

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#1879]
<img width="1162" alt="Screen Shot 2020-04-27 at 9 45 15 AM" src="https://user-images.githubusercontent.com/1226812/80397977-d2ef5580-886b-11ea-81b0-2b5f8386b9ed.png">
If "show frames" is checked, no content is ever displayed.
With show frames unchecked, everything is fine.

**Comment by kenzieschmoll** [comment]
is this at master and on the latest flutter?

**Comment by jacob314** [comment]
on master and latest flutter.

**Comment by kenzieschmoll** [comment]
This problem is still happening. @bkonyi it looks like this is an issue with bad input. Somehow in the html version of DevTools we are getting different results from the 'Timeline' stream than we are in the flutter version of DevTools.

In both [html_timeline_service.dart](https://github.com/flutter/devtools/blob/521dc51b668102cf876d8f73ebb5b3d637385371/packages/devtools_app/lib/src/timeline/html_timeline_service.dart#L42) and [timeline_service.dart](https://github.com/flutter/devtools/blob/521dc51b668102cf876d8f73ebb5b3d637385371/packages/devtools_app/lib/src/timeline/flutter/timeline_service.dart#L47), we listen the the 'Timeline' stream from the vm_service.

I added `print(json)` in both files as the first line within the for loop `for (Map<String, dynamic> json in events)` and got different output. The list of events from the html devtools app has repeated trace events while the list of events from the flutter devtools app does not.

Example sequence of events
Flutter DevTools (correct):
```
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456951056, ph: B, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456951127, ph: E, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456952161, ph: B, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456952207, ph: E, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456952817, ph: B, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456952854, ph: E, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456981831, ph: B, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456982946, ph: E, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50458518316, ph: B, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50458518456, ph: E, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50458518479, ph: B, args: {}}
```

Html Devtools (incorrect with repeated sequence):
```
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456951056, ph: B, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456951127, ph: E, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456952161, ph: B, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456952207, ph: E, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456952817, ph: B, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456952854, ph: E, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456981831, ph: B, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456982946, ph: E, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456951056, ph: B, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456951127, ph: E, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456952161, ph: B, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456952207, ph: E, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456952817, ph: B, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456952854, ph: E, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456981831, ph: B, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50456982946, ph: E, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50458518316, ph: B, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50458518456, ph: E, args: {}}
{name: MessageLoop::FlushTasks, cat: Embedder, tid: 17159, pid: 42223, ts: 50458518479, ph: B, args: {}}
```

The extra events break the chrome trace event nesting logic and break the timeline in html devtools. Any idea how we could be getting different events from the same stream? For the above example, the two versions of devtools were connected to the same app.

**Comment by kenzieschmoll** [comment]
It looks like we are getting multiple `Event` responses with the same list of timelineEvents (`event.json['timelineEvents']`).

**Comment by devoncarew** [comment]
Is it possible that the html version is subscribing to a stream more than once?

**Comment by kenzieschmoll** [comment]
As far as I can tell we only listen to the 'Timeline' stream in html_timeline_service.dart (for the html app at least).

**Comment by kenzieschmoll** [comment]
I think I found a fix. We were calling `_handleConnectionStart` twice. In the flutter app this didn't happen because the timing is different in terms of when we have connection and when the TimelineService is created.
