### ISSUE TITLE
Unknown thread shows up in timeline

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#1881]
Run a Flutter app in an ios simulator and you will see an empty "Unknown"
isolate at the bottom of the list of isolates.
We should consider hiding isolates without any profiling data or understand what this isolate is and why we don't have data for it.
<img width="1188" alt="Screen Shot 2020-04-27 at 10 13 46 AM" src="https://user-images.githubusercontent.com/1226812/80400621-ea304200-886f-11ea-940e-2c87a7be2cb5.png">

**Comment by kenzieschmoll** [comment]
the unknown "bucket" wouldn't show up if there weren't timeline events present. They are probably so small that they aren't visible at your current zoom level. As for naming, unknown corresponds to synchronous events that are neither from the UI thread nor the raster thread. We should probably store thread names and display those instead of using unknown

**Comment by blaugold** [comment]
I have submitted PR #3603 to fix this issue. 

It would also be great to display the `debugName` of isolates, but I'm not sure how complex that would be to implement.
