### ISSUE TITLE
Hot reload from app causes error

### ISSUE THREAD

**Issue by helin24** [flutter/devtools#1896]
Steps:
1. Run devtools using `pub global run devtools`. 
2. Run a flutter app (I used [gallery](https://github.com/flutter/gallery)) - `flutter run`
3. Press hot reload in the devtools top right bar

<img width="1663" alt="Screen Shot 2020-04-30 at 4 07 12 PM" src="https://user-images.githubusercontent.com/6379305/80767413-abfb8280-8afc-11ea-83c3-b12367df63ad.png">
In this screenshot I first tried hot reloading with the devtools button (failed), then tried hot reload on the command line by pressing 'r' (succeeded), then tried the devtools button again (failed)

**Comment by devoncarew** [comment]
I believe this has regressed, probably due to https://github.com/flutter/flutter/commit/4851888864348524b4065e18cd6e2597f906fd8d .

Those actions work via:
- the flutter command line tool contribute a vm service protocol extension - it connects to the VM via a debug connection, and indicates that it can provide the `ext.hotReload` command (or similar)
- the VM then advertises to other VM service protocol clients that a new service is available
- DevTools uses that info to display a 'reload' button
- when invoked, DevTools calls the `ext.hotReload` VM service protocol extension
- this call goes to the VM, which routes it to the flutter command line tool (the client that indicated it can provide that service)
- normally, the flutter tool would perform the reload service, and return the results to the VM

I think that last step is failing - I think the flutter CLI tool's impl of their service extension has regressed.

**Comment by devoncarew** [comment]
https://github.com/flutter/flutter/blob/0889e14361830b7922df58c199fba4fbe1563e00/packages/flutter_tools/lib/src/vmservice.dart#L157

**Comment by devoncarew** [comment]
Fixed in https://github.com/flutter/flutter/pull/56240 (in flutter master).
