### ISSUE TITLE
Network profiler not working after hot restart

### ISSUE THREAD

**Issue by ad-on-is** [flutter/devtools#1968]
I have an app that does a network request on startup, without users interaction.

1. Run app in debug mode and open Dart DevTools
2. Go to Network and press Record
3. Hot-Restart app
4. App executes a network-request on startup
5. Network profiler does not show the executed http request

but...

1. Run app in debug mode and open Dart DevTools
2. Go to Network and press Record
3. Press button in app to execute a network-request
4. Network profiler shows the http request

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.19628.1], locale en-AT)
    • Flutter version 1.17.0 at D:\Projects\Development\Flutter\flutter-sdk-win
    • Framework revision e6b34c2b5c (13 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\add\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.45.0)
    • VS Code at C:\Users\add\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • ONEPLUS A6013 • 2739990e • android-arm64 • Android 10 (API 29)
```

</details>

**Comment by kenzieschmoll** [comment]
@ad-on-is if you open the timeline page and click "Refresh" do you see HTTP events from the network request on startup?

@bkonyi IIRC, the network page only pulls traffic from the time the recording is started and beyond - does that sound correct? Is there any reason we shouldn't be recording traffic by default and pulling all network data that is available on the first request (from there after we could only pull data for the most recent polling interval)?

**Comment by bkonyi** [comment]
This is somewhat expected behavior given how network profiling is implemented. A hot restart will reset the state of the application, which also resets the `enableTimelineLogging` to `false`, its default value. We might want to add some state in tooling or DDS to reset this flag to its last value after a hot restart.

**Comment by maks** [comment]
@bkonyi thanks for the explanation as I just ran into this now too. Yes having the UI not show that the recording is being turned off is most confusing! 
For the time being I'm working around this by setting a break point, going into devtools to turn off recording, restarting my app, once the break point is hit, going back to devtools and starting recording again then continuing from the breakpoint.
The above works but is as inconvenient as it sounds. Is there anyway that the recording setting could be persisted across app restarts?

**Comment by kenzieschmoll** [comment]
we should be able to do this. We have similar functionality in DevTools for restoring the state of service extensions.

**Comment by kenzieschmoll** [comment]
@bkonyi I've been looking into this this morning. Implementing this "restore" functionality for the network extensions (http and socket) is proving to be more complicated because there are multiple extensions for each.

HTTP has get and set extension: 
`ext.dart.io.getHttpEnableTimelineLogging`
`ext.dart.io.setHttpEnableTimelineLogging`

Socket profiling has start and pause extensions:
`ext.dart.io.startSocketProfiling`
`ext.dart.io.pauseSocketProfiling`

Would it be possible to combine these extensions into one (much how the flutter service extensions are implemented. For example, calling `ext.flutter.showPerformanceOverlay` with a null value returns the current value, and calling `ext.flutter.showPerformanceOverlay` with a value sets the state of that extension.

If the network extensions were implemented in a similar fashion, it would be much cleaner and straight forward to track the value of these extensions in our tools. We'd like to be monitoring extensions that are capable of being getters and setters: `ext.dart.io.httpEnableTimelineLogging` and `ext.dart.io.socketProfiling`. This would also allow us to remove a couple methods from the service protocol.

**Comment by bkonyi** [comment]
Can you point me to where we handle this restore functionality for existing extensions? I'm surprised that having separate getters and setters makes things significantly more complicated.

Anyway, to answer your question, we could make that change with a major revision bump for the `dart:io` extensions version, although I don't know how I feel about overloading RPCs to be both getters and setters.

**Comment by kenzieschmoll** [comment]
We store current service extension states in service_manager.dart and restore them [here](https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/service_manager.dart#L695) after a hot restart. The issue is we will store the value of getHttpEnableTimelineLogging, but then that's not the one call to restore it. I'm trying to work around this with special casing, but will end up having to do something similar with sockets. Just doesn't feel like the cleanest solution, especially since the behavior is not consistent with flutter extensions. What are your concerns with overloading RPCs like it is done in flutter?

Additionally, though a slightly different problem, is that we don't receive a "changed" event when modifying the socket / http profiling status. For Flutter service extensions, we receive [ServiceExtensionChanged](https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/service_manager.dart#L560) events. This allows us to keep state consistent across different tools (IntelliJ + DevTools). Is there a similar event that we should be listening for when dart.io extensions are changed? If not, can we add one?

**Comment by kenzieschmoll** [comment]
@bkonyi an interesting thought @jacob314 mentioned was having DDS handle the business logic to restore service extensions on hot restart

**Comment by bkonyi** [comment]
I can't exactly give a good reason why I'm not a fan of overloading RPCs to be setters/getters, it might just be some C/C++ style that I've picked up over the years... If this is something we want to do and it's more consistent with other first-party service extensions I can make the change.

We don't currently send out events for changes made via the `dart:io` service extensions but that's something that should be easy to add. We already have an issue filed: https://github.com/dart-lang/sdk/issues/41823.

We could use DDS to deal with restoring state for the service extensions after a hot restart, but this wouldn't be something that we could generalize easily. We could start with handling state for some subset of known extensions, but if we want something more general that can be configured by clients that would take a decent amount of design work.

**Comment by jacob314** [comment]
It could make sense to design an api directly in dart:developer that lets you define service extensions that are getter setter pairs with state that should be restored. Should be a pretty small API surface.
