### ISSUE TITLE
Build a code size debugging tool for DevTools

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2043]
The tool should be able to load data from AOT / dart2js snapshots and display code size information. @peterdjlee

**Comment by xster** [comment]
Slight caveat. I suspect we're not going to be able to take any arbitrary .so/dylib or APK/IPAs and show the snapshot breakdown since the breakdown data is in a gen_snapshot byproduct rather than being in the snapshot itself. 

Also, for "hollistic-ness" it would be nice to break down the APK/IPA at the top level including the snapshot breakdown for a "one stop shop" analysis of the `flutter build` output artifacts.

**Comment by devoncarew** [comment]
> break down the APK/IPA at the top level including the snapshot breakdown for a "one stop shop" analysis of the flutter build output artifacts.

+1 to this; even if the UI we write is primarily focused on the AOT output, the thing that will matter most to users is the overall APK / IPA size. We should show that, and the main items contributing to the APK size, even if the tooling lets you dig into the AOT contribution more than the others.

**Comment by xster** [comment]
I think this can be closed now.
