### ISSUE TITLE
warning and error banners take up a lot of vertical space

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#2071]
The new warning and error banners take up a lot of vertical space:

<img width="1392" alt="Screen Shot 2020-06-11 at 8 14 17 AM" src="https://user-images.githubusercontent.com/1269969/84404463-b01ac580-abbb-11ea-820a-934d71fe85e2.png">

For several pages - like the timeline page and the memory page - vertical space is a scarce commodity.

I believe the intent here is to make the banner hard to ignore (which I think is generally good). I wonder if there are other ways we can emphasize the banners however, w/o taking up as much screen real estate? Some ideas:

- reduce the height of the banner; draw a 3-4 pixel wide border around the page contents in the same color as the banner (yellow or red)
- reduce the height of the banner, but have some aspect of the banner intrude on the page contents; this might be similar to the 'debug' banner on flutter devices

<img width="65" alt="Screen Shot 2020-06-11 at 8 21 15 AM" src="https://user-images.githubusercontent.com/1269969/84405190-a9d91900-abbc-11ea-9467-099c972f9003.png">

Other ideas?

cc @kenzieschmoll @raison00 @jacob314

**Comment by jacob314** [comment]
I would suggest making this a dialog that users have to manually dismiss or having the banner dismiss automatically after the first user interaction with the page or N seconds.

**Comment by raison00** [comment]
I agree, based on observing users seemingly ignoring the banner and letting it remain, rather than closing it, to have some aspect of the banner intrude on the page contents.   Here, is the border with a gap within the stroke.  The link color might work best with an update.
![updated-warning](https://user-images.githubusercontent.com/8105802/84420000-42c46000-abce-11ea-924c-2d6e3e68abd2.png)

**Comment by kenzieschmoll** [comment]
These banners have been densified. Closing as complete.
