### ISSUE TITLE
RTL alignment in layout explorer

### ISSUE THREAD

**Issue by azeztd1** [flutter/devtools#2138]
Dart Devtool layout explorer is miss alignment with locale and RTL option 
locale option in the code is :

`locale: Locale('ar', 'AE'),`

main direction for all of the app is RTL

DevTool:
![image](https://user-images.githubusercontent.com/44948937/85986536-1776a900-b9f5-11ea-9110-3bd3b2795ed6.png)

UI:
![image](https://user-images.githubusercontent.com/44948937/85988109-40983900-b9f7-11ea-9cad-70d948612bed.png)

so the main problem is layout explorer should be mirrored so result would be true.

Of course thanks for the great new DevTool.

**Comment by jacob314** [comment]
Fyi @adalberht

**Comment by adalberht** [comment]
@jacob314  oh yes I totally missed this one 🙇  
I believe we have `TextDirection` property in the `FlexLayoutProperties` that contains all the logic for computing the layout calculation used in the LayoutExplorer, but it's currently not used anywhere in the computation since I totally forgot to implement the rtl alignment one. But I need to make sure whether this `TextDirection` properties matches the current user locale or not, I believe it does.

I can take up this issue if you want!
