### ISSUE TITLE
[travis] use dart sdk from flutter sdk

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2249]
We are pulling a dart sdk that does not match the version of dart flutter is using. We should make sure travis is using the dart sdk from flutter

**Comment by christopherfujino** [comment]
I'm pretty sure the actual issue was [this](https://github.com/flutter/flutter/issues/62146), which has since been fixed (by issuing a new dev version of Flutter). Having the Dart SDK installed in the environment **shouldn't** interfere with flutter. We're careful in the CLI tool to always use absolute paths when calling the Dart SDK.

**Comment by devoncarew** [comment]
https://github.com/flutter/devtools/pull/2267 Should address this. We'll need to discuss whether we should test against flutter master or flutter dev.

**Comment by kenzieschmoll** [comment]
@devoncarew did this issue get resolved?

**Comment by devoncarew** [comment]
Yup - closing.
