### ISSUE TITLE
[new navigator] - when navigating to the app size tab, the stand alone app size page is rendered

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2468]
navigating to the app size tab should render the app size page in the context of the entire devtools app (e.g. tab bar, footer, buttons in top right should all still be present). 

Instead, navigating to the app size tab navigates to the stand alone app size route that is used when navigating to the app size tool from the landing screen

@DanTup

**Comment by DanTup** [comment]
This happened because navigations are driven by the URL now and the URL for the standalone page was the same as the one for the tabbed screen.

I've given them different IDs now (and commented why) - see https://github.com/flutter/devtools/pull/2470 though if we think we may end up with more than just this one we could consider giving the tabbed screens all a prefix (eg. `/app/$screenId` or something) to avoid conflicts instead.
