### ISSUE TITLE
DevTools url has fragment and query parameters in the wrong order

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2475]
Current: `http://127.0.0.1:9100/#/timeline?ide=IntelliJ-IDEA&uri=http%253A%252F%252F127.0.0.1%253A59289%252FolleV5zVaVs%253D`

Expected: `http://127.0.0.1:9100/?ide=IntelliJ-IDEA&uri=http%253A%252F%252F127.0.0.1%253A59289%252FolleV5zVaVs%253D#/timeline`

In the current form, Uri.parse gets the incorrect values for `fragment` and `queryParameters`

**Comment by kenzieschmoll** [comment]
FYI @DanTup

**Comment by DanTup** [comment]
Although it's a bit unintuitive, this is expected. It's not how a URL normally would be formed but in Flutter we only get the fragment part, and we had a convention of putting a query string in it for pass our data around.

Since the routing changes, we handle the URI parsing in `DevToolsRouteInformationParser.parseRouteInformation` where `routeInformation.location` will be just the fragment, eg.:

When at page: `http://localhost:50593/#/?hide=debugger&ide=VSCode&theme=dark&uri=http%3A%2F%2F127.0.0.1%3A50288%2FERZc7YGNhyo%3D%2F`
`routeInformation.fragment` is: `/?hide=debugger&ide=VSCode&theme=dark&uri=http%3A%2F%2F127.0.0.1%3A50288%2FERZc7YGNhyo%3D%2F`

Which we then parse into a URI to get `path` (`/`) and `queryParameters`.

Have you found code that is parsing the URI directly? If so, we should update it to use the params from the routing (since this should also work better for non-web too).

(As an aside, while looking at this I noticed `hide=debugger` isn't working so I'm just looking into that - I don't think it's a result of this though as I can see it in `params`).

**Comment by kenzieschmoll** [comment]
Now there is another '?' character in the url that is causing url parsing issues when trying to show the DevTools survey
e.g. 'http://127.0.0.1:9103/?#/?'

related: https://github.com/flutter/website/pull/6696

**Comment by DanTup** [comment]
@kenzieschmoll are you looking at this or did you want me to? If me, how do you end up with the bad URL? Is the goal to fix that, or just handle it better when it happens?

**Comment by kenzieschmoll** [comment]
@DanTup if you have time to take a peek, feel free! The bad url happens by default right now. I just opened DevTools to the connect screen and got the url with two '?' chars. The logic in #3574 shows an example of where it would be nice if we could just parse the Uri with `Uri.parse` and be able to grab the fragment directly instead of doing what we currently have to do which is manipulate the string with indexOf calls to find what we are looking for. This works, but is not robust.

**Comment by DanTup** [comment]
How are you starting the app? If I run from VS Code by pressing `F5` in the `devtools_app` folder, I only see one `?` in the URL:

![Screenshot 2022-01-20 at 10 16 14](https://user-images.githubusercontent.com/1078012/150319342-03f8515d-988c-4095-8697-81c11e02c1af.png)

I'm using Flutter 2.9.0-1.0.pre.384

**Comment by kenzieschmoll** [comment]
I was using a release build:
`./tool/build_release.sh `
`dart packages/devtools/bin/devtools.dart`
