### ISSUE TITLE
P1: Surface layout errors in Inspector

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2503]
When inspecting a screen with errors (e.g. renderflex overflow), surface these errors in the inspector. We could highlight the widget names in red and provide a way to navigate to the problem widget.

**Comment by kenzieschmoll** [comment]
@jacob314 do we have information about which widgets triggered errors? do we get this information on a vm-service stream that?

**Comment by DanTup** [comment]
@kenzieschmoll @jacob314 if the same error is thrown multiple times, the URL with the `inspectorRef` is the same:

> &inspectorRef=inspector-0

However that ID doesn't seem to occur anywhere else in the structured error (all `objectId`s in the errors properties are different to this). It seems like we need to be able to de-dupe these to make the error badge count accurate (eg. it goes up by two when I run my sample overflow app, even though the inspect URL is the same) and only list any errored widgets once.

**Comment by DanTup** [comment]
Is something like this what you had in mind?

![Screenshot 2021-01-26 at 15 06 04](https://user-images.githubusercontent.com/1078012/105862746-0c661480-5fe8-11eb-90bf-0798d88803ff.png)

I'm not sure if we have enough info to highlight the highlight the item in the tree in some way, though I figured showing the error list would be useful in case the errored item is collapsed/offscreen.

I have a few issues though:

- It's not clear when an error becomes stale - they build up in the list and clicking them does nothing (eg. after you'd reloaded). We could clear them on reload/restart, but that's probably just masking the issue (since they could presumably be invalidated by a user navigating around the app)
- I can't figure out how to give the errors an obvious mouse pointer to make it clear they're clickable (the tree has pointer cursors, but I couldn't find where that's done)

**Comment by kenzieschmoll** [comment]
In the future we could add the inspector ref Id as a field to the structured error json. But for the first implementation we will need to get that info from the parsed uri. 

I agree we should de-dupe the errors. We could do this in the error badge manager by storing a set of the active error causing inspector refs in the tree. When the inspector tree is refreshed, we could clear this list and the badge count, or maybe a better solution would be to clear the errors that are no longer in the tree and keep the ones that are.

In the error badge manager code, we badge the inspector for more errors than just the overflow errors. Perhaps to start we should just badge errors for the overflow errors (the ones we have added DevToolsDeepLinkProperty for) and keep things simple for the MVP.

**Comment by DanTup** [comment]
> for the first implementation we will need to get that info from the parsed uri

SGTM, that's what I've done so far.

> I agree we should de-dupe the errors. We could do this in the error badge manager by storing a set of the active error causing inspector refs in the tree. When the inspector tree is refreshed, we could clear this list and the badge count, or maybe a better solution would be to clear the errors that are no longer in the tree and keep the ones that are.

Right now, I've appended any errors as they come in (assuming they're valid at the time), and in the "Refresh tree" action wipe out any that are no longer valid. Collecting the valid IDs seems to be async, so I don't know how expensive that is. We're also not noticing any errors that become invalid prior to refreshing the tree - though that might be expected (I guess the tree doesn't update until you press refresh?).

> In the error badge manager code, we badge the inspector for more errors than just the overflow errors. Perhaps to start we should just badge errors for the overflow errors

That's what I'm doing now - only if we managed to extract an `inspectorRef` to we update the badge (since the badge is now equal to the errors we're tracking).

I've opened a draft PR at https://github.com/flutter/devtools/pull/2630 for some feedback.
