### ISSUE TITLE
Devtools ui not showing 

### ISSUE THREAD

**Issue by MrAdityaAlok** [flutter/devtools#2523]
![Screenshot_2020-11-29-01-55-45-074](https://user-images.githubusercontent.com/73517616/100525369-45e7f280-31e6-11eb-8894-bed0c4f30c96.jpeg)
## OS
Android 9 -arm64 (in termux)
DevTools Version 0.9.3+4.

## Problem
When I go to chrome, devtools ui do not appear....(as in the picture above)
Tried to refresh, switching to desktop site , but nothing happened.

**Comment by jacob314** [comment]
Thanks for reporting. Can you clarify why you want to run DevTools on an Android device? We aren't really expecting DevTools itself to be run on a physical Android or iOS device. Even if it works, I expect performance may be slow due to how dense the UI is. If you really want to run devtools on an Android device you could probably run it as a native Flutter app. We run it as a native Flutter Desktop app while developing.
Fyi @hterkelsen in case there is something simple we can do to make a a CanvasKit Flutter Web app work on mobile.

**Comment by MrAdityaAlok** [comment]
> Thanks for reporting. Can you clarify why you want to run DevTools on an Android device? 

Well, I was developing a dart application on my Android device . So, I thought it would be nice if I was able to run DevTool on Android but although  it started, Chrome could not load it's ui 🤨

> If you really want to run devtools on an Android device you could probably run it as a native Flutter app


I would try it out...  🙂
But still Hoping,  soon it would be available for Android device.....🤗
Thank you for your suggestion ☺️
