### ISSUE TITLE
DevTools keeps loading without any errors

### ISSUE THREAD

**Issue by easeccy** [flutter/devtools#2568]
I'm debugging a Flutter web app. I can't open DevTools. I tried VS Code and console (by pressing v), it does not give any errors.

```
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
    • Flutter version 1.25.0-8.1.pre at C:\flutter
    • Framework revision 8f89f6505b (8 days ago), 2020-12-15 15:07:52 -0800       
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\enes\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88

```

**Comment by kenzieschmoll** [comment]
Can you try to open DevTools via `flutter pub global activate devtools; flutter pub global run devtools`?

**Comment by easeccy** [comment]
I followed [this ](https://flutter.dev/docs/development/tools/devtools/cli) guide and it worked. Other options are still broken for me, I have to do this manually. VS Code and command line shortcuts does not work.

**Comment by kenzieschmoll** [comment]
Are you still broken if you upgrade your flutter to latest beta? or even latest master channel?

cc @DanTup

**Comment by DanTup** [comment]
What happens when you try to launch using the button in VS Code? Does any notification appear in the bottom right corner? Could you try capturing a log?

- Ensure "Dart DevTools" is not visible in the status bar when you have a Dart file open (if it is, restart VS Code)
- Start debugging your app using the Run menu
- Run the **Dart: Capture Debugging Logs** command from the command palette
- Click the DevTools icon on the debug toolbar
- Wait a little time for DevTools to try to launch
- Click **Cancel** on the logging notification to stop logging and open the log file

Thanks!

**Comment by easeccy** [comment]
Issue resolved after I switched master and switch back to beta. I can start dev tools from VS Code.
