### ISSUE TITLE
No debugger page or tab

### ISSUE THREAD

**Issue by Kabilan21** [flutter/devtools#2584]
I was able to switch the debugger tab before. But now, the debugger tab is not visible in the browser and I couldn't make use of it.

**Comment by kenzieschmoll** [comment]
Can you add some details about how you are running your application? What is the target platform (mobile, web, desktop, etc.)? If you are running in profile mode you should not expect to see the debugger.

**Comment by Kabilan21** [comment]
The target platform is android. I tried both in debug mode and in profile mode. But I couldn't see the debugger tab. I attached a screenshot of the dart dev tool opened in the browser.
![Screenshot (184)](https://user-images.githubusercontent.com/53993282/103984353-f6b1bc00-51ac-11eb-8f10-d7545ce6bc16.png)

**Comment by kenzieschmoll** [comment]
are you launching from VS Code? I see "hide=debugger" in the URL. @DanTup perhaps we should stop hiding the debugger on launch from vs code?

As a temporary workaround, you can remove the `hide=debugger` query parameter from the URL and the debugger page will show up.

**Comment by Kabilan21** [comment]
Thank you.It worked

**Comment by DanTup** [comment]
There are some issues that need resolving before using two debuggers will work correctly (right now they both will try to do some things like sending breakpoints and resuming when the app restarts). There's an open issue about it at https://github.com/flutter/devtools/issues/731.

Removing hide=debugger from the URL is a reasonable temporary workaround, but it's worth bearing in mind you may see issues doing this. If you want to use the DevTools debugger instead of VS Code's, you may be better running the app "without debugging" from there, or from the terminal (although if you're doing this because of issues with the VS Code debugger that should probably be fixed, please let me know!).
