### ISSUE TITLE
Decode and display images in the network profiler for HTTP/HTTPS responses

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#2603]

**Comment by bkonyi** [comment]
As discussed offline, we've hit a limitation with the current timeline based HTTP profiling due to the 32KiB ring buffer being much too small to record HTTP response data. In theory, this could be worked around by using an endless buffer, but that's not something we'll want to do by default due to memory implications.

We'll likely want to move to a hybrid timeline/RPC based profiling approach, where we still log HTTP events to the timeline but don't include body data. These events would also be available via a service extension, in addition to request/response bodies for each HTTP request/response.

This will involve a decent amount of work, so it's unlikely this can be done before 2.0.

**Comment by bkonyi** [comment]
Blocked on https://github.com/dart-lang/sdk/issues/44950.
