### ISSUE TITLE
There is no way to exit widget inspector by keyboard in vscode

### ISSUE THREAD

**Issue by jeiea** [flutter/devtools#2775]
## Steps to reproduce
1. Debug any flutter project.
2. Open widget inspector in vscode.
3. Select any widget by click
4. Press Cmd+1, Cmd+Shift+P, F1, Cmd+W, etc.

## Expected behavior
Focus first editor group or open command pallete, close widget inspector.

## Actual behavior
Widget inspector consumes all keypress and nothing happens.

**Comment by kenzieschmoll** [comment]
CC @DanTup @jacob314

**Comment by DanTup** [comment]
This sounds a bit like https://github.com/microsoft/vscode/issues/104329, though that's recently been fixed and I can still repro this in VS Code Insiders. I've added a comment there to see if there's anything specific webviews are supposed to do to pass the keypresses back up to VS Code.

**Comment by jacob314** [comment]
Not sure the priority of this. If this matters we could have DevTools dispatch an event over the VM Service that you can listen to in VSCode to determine when to close DevTools or we could dispatch all key pressed from DevTools over the VMService as that could make it easier for you to keep the keyboard shortcuts consistent with VSCode. Fyi @helin24 to see if keyboard shortcuts for closing tool windows work for DevTools embedded in IntelliJ.

**Comment by jeiea** [comment]
I can't sure it's really same issue. I can move editor, open command pallette, close window by keyboard in release note page. microsoft/vscode#104329 seems to be reproduced in windows, but I don't know that is same to macos.

**Comment by DanTup** [comment]
@jacob314 I made this work with some comments from the linked issues. Usually VS Code handles keypresses for webviews and passes them up to VS Code. When using an iframe, this doesn't work, so the keypress needs to be passed up from the iframe to the parent frame. Due to CORS restrictions, this has to be done via `postMessage`.

So if I put this into the DevTools index.html:

```js
document.addEventListener('keydown', (e) => {
    const data = {
        altKey: e.altKey,
        code: e.code,
        ctrlKey: e.ctrlKey,
        isComposing: e.isComposing,
        key: e.key,
        location: e.location,
        metaKey: e.metaKey,
        repeat: e.repeat,
        shiftKey: e.shiftKey
    }
    window.parent.postMessage({ command: 'keydown', data: data }, '*');
});
```

And then this into the HTML chunk Dart-Code renders with the iframe:

```js
window.addEventListener('message', (event) => {
	const message = event.data;
	switch (message.command) {
		// snip
		case "keydown":
			window.dispatchEvent(new KeyboardEvent('keydown', message.data));
			break;
	}
});
```

This appears to resolve the issue. Is it reasonable to commit that into DevTools? (note DevTools can only be hosted inside iframes if the server was started with `--allow-embed`).

**Comment by jacob314** [comment]
I have some security concerns with that. To make it safer can you restrict what is dispatched so not all keyboard events are dispatched and can you only make it apply if a valid vm service url was passed in to the iframe? Otherwise someone could possibly use this to snoop on how a user interacted with devtools by adding the iframe to a malicious webpage.

**Comment by DanTup** [comment]
This fix required a change in both the VS Code extension and DevTools, so will show up only after both have been released.
