### ISSUE TITLE
Improve the experience for non-Flutter apps (hide Inspector, default to different tab, etc.)

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#283]
I've fixed the JS error (#277) but there are some decisions outstanding about what should happen when we get a non-Flutter app. We currently default to the Inspector, but probably that tab should be hidden.

**Comment by DanTup** [comment]
@devoncarew @jacob314 I was going to look at doing this similar to `hide=debugger` (since the editor knows if it's launching for a Flutter/non-Flutter app), however it occurs to me that once the user has launched, it's feasible that they disconnect/reconnect to a different type of app, so hiding/disabling the Inspector based on the project that *launched* the browser may not be best.

So, we could leave this up to the editor (eg. VS Code can add `#logging` to the URL when spawning for a non-Flutter session) and then we could just *disable* the Inspector/Timeline button based on the VM service connection when it connects? The only thing is, it'd then be weird to re-order the buttons, so it would be slightly inconsistent with the disabled Debugger button (which gets shunted to the end). WDYT?

**Comment by jacob314** [comment]
I think we should determine whether the application is flutter or not based on just the VM Service extensions present rather than pushing more logic into the VSCode and IntelliJ tools.
The Inspector should show up disabled until one of the ext.flutter.inspector extensions is available. This will also fix the bug where the inspector displays an error in the JS console if run on a profile mode application (profile mode does not support the inspector).

For the issue of changing a port, I do wonder whether we should support changing the port if a user launched the devtools from VSCode or IntelliJ. I don't think we really want a user to be changing the port in one of those environments. In those cases if the port is closed we just want to display "that the flutter application disconnected, check your IDE to see what happened" rather than prompting the user to enter a port which they have no idea what to enter for.
