### ISSUE TITLE
Order in CPU Profile Flame Chart is inconsistent

### ISSUE THREAD

**Issue by goderbauer** [flutter/devtools#2855]
Somehow the order of events shown in the Flame Char of the CPU Profile doesn't look correct. I would assume that A is ordered to the left of B if A happens before B. However, in the graph that isn't the case. Example: `flushLayout` happens before `flushPaint`, yet it's ordered the other way around in the flame chart, see screenshot:

![image](https://user-images.githubusercontent.com/1227763/113343224-646d1000-92e4-11eb-9ba0-a7ab8e388315.png)

**Comment by kenzieschmoll** [comment]
CPU profiles aren't actually ordered by time. The left to right order is arbitrary because CPU samples are aggregated to show common code paths. Without aggregating common samples, the profile would not be readable and it would be virtually impossible to recognize hot spots in your app (as you'd have to manually look for code paths that show up a lot).

You can read about this in our docs here: https://flutter.dev/docs/development/tools/devtools/cpu-profiler#flame-chart, or see similar information from the AS documentation https://developer.android.com/studio/profile/cpu-profiler#flame_chart

**Comment by kenzieschmoll** [comment]
closing as WAI
