### ISSUE TITLE
safari show white blank page

### ISSUE THREAD

**Issue by allanGoldZhiKang** [flutter/devtools#2856]
![image](https://user-images.githubusercontent.com/29418848/113389000-da937480-93c1-11eb-8b8a-b6a8855e8c21.png)

**Comment by allanGoldZhiKang** [comment]
![image](https://user-images.githubusercontent.com/29418848/113389053-f565e900-93c1-11eb-8064-04ed1877fa56.png)

**Comment by jacob314** [comment]
Fyi @DanTup 
Safari should work better than this.

**Comment by DanTup** [comment]
Using the latest bleeding-edge build of Dart and running `dart devtools` then trying to open in Safari I also get a quite page. The error looks like this:

![Screenshot 2022-12-13 at 10 51 41](https://user-images.githubusercontent.com/1078012/207298857-cee6a3d9-abba-4586-963f-556a05646f4d.png)

![Screenshot 2022-12-13 at 10 52 37](https://user-images.githubusercontent.com/1078012/207298865-fe1d7680-07fa-4a97-9cf5-18d4ecfe2b4e.png)

I found that regex in the syntax highlighting grammar.. I don't know why it's ok in Chrome but broken in Safari, but I'll do some digging..

**Comment by DanTup** [comment]
I have a fix up at https://github.com/flutter/devtools/pull/4938 that will just disable syntax highlighting if it fails to initialize (since making it work without negative-lookbehinds will be significant effort). With that change, DevTools loads and works in Safari:

![image](https://user-images.githubusercontent.com/1078012/207322555-5c57f700-7b08-4175-8ad8-084fa579ac1e.png)
