### ISSUE TITLE
Testing: Performing a hot-restart in integration tests appears to not restart inspected application

### ISSUE THREAD

**Issue by rrousselGit** [flutter/devtools#3007]
It appears that after calling:

```dart
await env.flutter.hotRestart();
```

in a test, then the inspected application is stopped and never restarted.

This is apparent because after the hot-restart, the inspected app's `WidgetsBinding.instance` is `null`.

**Comment by elliette** [comment]
Closing, I believe the correct way to perform a hot-restart in an integration test (because this is what our integration tests are currently doing) is to call

`serviceManager.performHotRestart()`

See for example https://github.com/flutter/devtools/blob/eaef4d39917babb220937630173d3f0386efa9bb/packages/devtools_app/integration_test/test/live_connection/service_extensions_test.dart#L224
