### ISSUE TITLE
feature request: copy http request "as curl"

### ISSUE THREAD

**Issue by maks** [flutter/devtools#3042]
Many (most?) HTTP inspection tools, proxies, etc have a "copy as curl" feature, eg. Charles Proxy:
![charles-curl](https://user-images.githubusercontent.com/71999/118735389-b1507a00-b883-11eb-8569-ee42fe591ec8.png)

and [Chrome DevTools](https://umaar.com/dev-tips/3-copy-as-curl/).

[This package ](https://pub.dev/packages/curl) could be a good starting point for this, though I believe it currently does not yet support query params.

Even round-tripping could be possible as @csells has [added Dart support for going from curl to Dart http client syntax](https://github.com/NickCarneiro/curlconverter/blob/master/generators/dart.js).

**Comment by codenoobforreal** [comment]
need this feature.

**Comment by exaby73** [comment]
+1 on this

**Comment by csells** [comment]
+1! although I may be bias : )

**Comment by cyrilnoah1** [comment]
+1 
This seems to have been opened a year ago, any update on this?

**Comment by jankuss** [comment]
@kenzieschmoll I'm working on this - Can you please assign this to me?

I intend to add a "Actions" column on the right of each network request. When you click on it, a popup opens which shows the different actions for that request:

https://user-images.githubusercontent.com/1659532/168482500-d2c89453-40f0-4d51-8e4c-2ea7d76a1c23.mov

Do you think I can proceed with such a solution, or do you have a better idea on how we should build this? I tried to build this by opening a context menu with right click, but this doesn't behave well within a browser.

**Comment by kenzieschmoll** [comment]
hi @jankuss. thanks for working on this! I'll assign it to you. Adding a context menu sounds good to me. Longer term, right click would be the preferred solution but until Flutter Web has better support for this, an explicit context menu button is fine. A couple pieces of feedback:
1) let's use a vertical three-dot icon instead of horizontal to be consistent with other parts of DevTools
2) only adding the menu button to the selected request may make the UI appear less busy
CC @InMatrix

**Comment by InMatrix** [comment]
> only adding the menu button to the selected request may make the UI appear less busy

+1

**Comment by csells** [comment]
Nice! This will go very well with this: https://curlconverter.com/#dart
