### ISSUE TITLE
flaky test: integration, debugging, lists scripts

### ISSUE THREAD

**Issue by devoncarew** [flutter/devtools#320]
integration, debugging, lists scripts

https://travis-ci.org/flutter/devtools/jobs/496269997#L626

```
00:56 +7 -1: test/integration_tests/integration_test.dart: integration debugging lists scripts [E]
  Expected: non-empty
    Actual: []
  
  package:test_api                           expect
  test/integration_tests/debugger.dart 45:5  debuggingTests.<fn>
  ===== asynchronous gap ===========================
  dart:async                                 _AsyncAwaitCompleter.completeError
  test/integration_tests/debugger.dart       debuggingTests.<fn>
  ===== asynchronous gap ===========================
  dart:async                                 _asyncThenWrapperHelper
  test/integration_tests/debugger.dart       debuggingTests.<fn>
```

**Comment by DanTup** [comment]
When I first started getting the tests running on Windows, this test would always fail, and adding a delay fixed it. However, it now always fails on Windows, until I add lots of `print` statements to try and track it down, and then it always passes 🤷‍♂️

**Comment by jacob314** [comment]
I'm seeing a lot of flakes on this test as wel on the build bots.
I was just chatting with a former coworker on a team that has really stable tests and what they require is that all tests are able to run 5000 times in a row without flaking. It will be a bit harder for us to achieve this with open sourced testing tools but lets use it as a target for where we want to go. We can put together some basic tools to trigger that number of reruns. As a starting point, if a test does flake we can require that a fix for the flake shows that the flake is really fixed if rerunning the test 5000 times locally before we assume that the test is fxed. I have been guilty of thinking tests are deflaked long before the 5000 test threshold so I think this will help us really drive to have stable tests that we trust.

**Comment by DanTup** [comment]
I've been running this one repeatedly on my fork on Travis in the background using a shell script (https://travis-ci.org/DanTup/devtools/builds). When I added a lot of logging, it didn't seem to happen (but that could've been coincidence) so I'm trying to add logging more gradually en ensure it's still flaking as I go (it seems like a race, and too much logging might affect it).

It's going to be hard to ever run a test 5000 on Travis (which is where we seem to see the failures most, though I don't know if that's just because the tests run much more there).

It looks like the test package may have some way to run tests multiple times (like devicelab's flaky):

https://github.com/dart-lang/test/blob/ac21330338e0a7ad68fb19058bb92260706dd6cf/pkgs/test_api/lib/src/frontend/retry.dart

Maybe we can use this to mark flaky tests so we have a convenient way of knowing if failures are due to tests we know are flaky (and are hopefully trying to fix) vs more legit failures?

**Comment by DanTup** [comment]
Ok, I think I understand why this test flakes now. The test runs the test app and checks the Scripts view contains scripts. However, it doesn't wait for any event (for example hitting a breakpoint) so there's a race between the test looking at the scripts, and the scripts view actually being populated (which happens when the isolate events fire).

```
===     VM does supports getScripts =)    ===
chrome • console:log • enumerating scripts view // <-- TEST READS SCRIPTS
chrome • console:log • [{"id":4,"result":[]}]
00:55 +7 -1: test/integration_tests/integration_test.dart: integration debugging lists scripts [E]
  Expected: non-empty
    Actual: []
  
  package:test_api                           expect
  test/integration_tests/debugger.dart 47:5  debuggingTests.<fn>
  // ...
chrome • console:log • showing 213 scripts // <-- DEBUGGER POPULATES SCRIPTS LIST
```

Some possible options for fixing:

- Wait until the scripts view has been populated (may require firing some new event)
- Wait in a loop up to x seconds for the script to appear (`waitFor`)
- Break for some other event that we know happens late enough that scripts should be populated (an easy one would be a breakpoint we set in the app, though it may make the test more complicated)

In an attempt to fix the flake, I'm going to try doing **2** and re-running on my fork a bunch of times, but we can change it to another option if we have a preference.
