### ISSUE TITLE
Special character ⌘ renders incorrectly on web

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#3352]
![image](https://user-images.githubusercontent.com/21270878/132905009-141ce7fd-3baa-4542-8ebd-4a1448454539.png)

This seems to be a known Flutter issue, and happens when Canvaskit is the renderer:

* https://github.com/flutter/flutter/issues/79172
* https://github.com/flutter/flutter/issues/77465
* https://github.com/flutter/flutter/issues/76473

One solution is to use "cmd" until this is resolved in Flutter.

**Comment by sperochon** [comment]
Same issue here.

The fix is to use a font that includes this special character as indicated in the logs:
`Could not find a set of Noto fonts to display all missing characters. Please add a font asset for the missing characters. See: https://flutter.dev/docs/cookbook/design/fonts`

I've used 'Inter' font and it is now displaying fine.
https://fonts.google.com/specimen/Inter?query=inter&preview.text=⌘&preview.text_type=custom

**Comment by elliette** [comment]
Fixed in https://github.com/flutter/devtools/pull/3353
