### ISSUE TITLE
Scrollbar issue on debugger page

### ISSUE THREAD

**Issue by xu-baolin** [flutter/devtools#3372]
![image](https://user-images.githubusercontent.com/61075224/133750272-584ad6ae-4f2e-40c1-8d49-cec2840ea9d1.png)
### Video

https://user-images.githubusercontent.com/61075224/134300303-d52e2a9f-74ce-46b0-a2e4-d1fc2eba276d.mp4

windows + Chrome

**Comment by jacob314** [comment]
Fyi @kenzieschmoll @elliette. Looks like we still have some scrollbar issues.
@xu-baolin, thanks for the bug report! Can you provide some more details about the bad srollbar behavior you are seeing? If you interact with the debugger page, does the phantom scrollbar go away? What happens if you resize the window? Sending an animated gif could also help clarify these sorts of questions.

**Comment by xu-baolin** [comment]
> Fyi @kenzieschmoll @elliette. Looks like we still have some scrollbar issues.
> @xu-baolin, thanks for the bug report! Can you provide some more details about the bad srollbar behavior you are seeing? If you interact with the debugger page, does the phantom scrollbar go away? What happens if you resize the window? Sending an animated gif could also help clarify these sorts of questions.

Updated.
