### ISSUE TITLE
Couldn't connect to flutter web 

### ISSUE THREAD

**Issue by Puspharaj** [flutter/devtools#3376]
`flutter run -d web-server --web-port 5000 `

I can see my app up and running at http://localhost:5000/#/.

But i cannot connect Dart dev tools,  it says connect to running app. If i provide the url, exception throws "cannot connect".

PS: dont ask for sample code you can mimic the issue with sample application.

**Comment by kenzieschmoll** [comment]
@elliette is this expected to work outside of google3?

**Comment by mark-dropbear** [comment]
I hope so! Trying to enable using Github codespaces for Flutter development and this is a key requirement to unlock that

**Comment by mark-dropbear** [comment]
Hmm just to double check a couple of assumptions here as it sounds like I may potentially be on the wrong track here.

- Github codespaces is a managed dev environment (comparable to the new idx.dev project) that allows me the ability to specify my dev environment as a Dockerfile (example of one I am using here: https://github.com/dropbear-software/crm/blob/main/.devcontainer/Dockerfile) 
- That environment is then exposed to me via a HTTP interface 

Therefore unless I am missing something important here I can't(?) really tell it to use Chrome as it's running inside of a docker container and it wouldn't make sense to include one in there either because how would it launch?

Going back to that idx.dev reference it looks like they have already solved that specific problem that I am encountering here, just not sure how but I am very keen to get an invite and start using it ;)

**Comment by elliette** [comment]
Are you experiencing this issue or having you found a workaround? If not feel free to re-open so we can investigate. Thanks!
