### ISSUE TITLE
DevTools loads in an invalid state if the main isolate is not yet ready

### ISSUE THREAD

**Issue by matt-ragonese** [flutter/devtools#3391]
Though maybe an edge case, it appears possible to launch DevTools via an Observatory URL before the VM's main isolate is ready. This can result in (1) a long pause when tapping the "CONNECT" button and/or (2) the "Debugger" screen not appearing once DevTools loads.

**Comment by kenzieschmoll** [comment]
From a conversation with @bkonyi: We should wait for the isolate runnable event on isolate stream. 

We may need to show a connection spinner until this event comes in so that we communicate to the user that something is happening. Right now, the connect button is just disabled and it looks like DevTools is broken

**Comment by kenzieschmoll** [comment]
@bkonyi I tried to wait for the IsolateRunnable event, but this still doesn't solve the problem. The Portmon library the conditional screen checks for is still not available at this time. Any other ideas for how we can guarantee that the library will be available?
