### ISSUE TITLE
Hide enhance tracing options for versions of flutter where they are not available.

### ISSUE THREAD

**Issue by InMatrix** [flutter/devtools#3498]
I was running a debug build of the perf_diagnosis app in a iOS simulator, and I found "Track Layouts" and "Track Paints" options grayed out. Is this expected?  

![image](https://user-images.githubusercontent.com/348942/141542745-8f8c9e89-1a46-4427-9a39-1fcbfa66ef8b.png)

**Comment by kenzieschmoll** [comment]
yes, those options will be greyed out if the underlying service extension is unavailable. I expect this is because you are on an older version of flutter. Perhaps we should hide these options instead of greying them out for versions of flutter prior to when these service extensions were added (only a couple weeks ago)

**Comment by InMatrix** [comment]
I'm on the latest stable (2.5.3), which seems to be four weeks old. Hiding unavailable options sounds good to me.

**Comment by kenzieschmoll** [comment]
This is obsolete now that devtools is tightly coupled to the Flutter SDK.
