### ISSUE TITLE
Spiked frame in bar chart causes other bars to be very small

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#358]
If you encounter an extremely slow frame, the plotly bar chart increases the scale of the y-axis to accommodate this spike in the data. This makes the rest of the "normal" frames or not-as-slow frames to be very small and uneasy to click or visualize.

<img width="1392" alt="screen shot 2019-02-25 at 1 29 09 pm" src="https://user-images.githubusercontent.com/43759233/53370105-aeaf8600-3901-11e9-96e9-829346e608e0.png">

Not sure what the best solution is for this, but I don't think it is a very good user experience as is.
@terrylucas

**Comment by terrylucas** [comment]
Yes its a problem.  I think the best solution is to switch to a logarithmic scale e.g.,

![image](https://user-images.githubusercontent.com/2055873/53575378-468db980-3b26-11e9-897b-5e2436edfd82.png)

I don't think in general we want to have our y-axis in log scale but if a duration is larger than the current y-axis scale by 100 or more we would automatically switch from a linear to a log scale.  What do you think?

@jacob314

**Comment by terrylucas** [comment]
Thought of another solution.  Could cap any particular bar to say 100 and on hover we show its real value.  Kind of misleading, but is janky and marked as such, but its certainly would stick out as a problem.  I prefer the y-axis log scale.

**Comment by kenzieschmoll** [comment]
I prefer the logarithmic scale solution. I think that will be less misleading than a hard cap.

**Comment by jacob314** [comment]
Lets loop in @inmatrix for this. Keep in mind that our users don't always have the math backgrounds we do so something like a log scale could be confusing. That said, a log scale would keep everything in view so I really like it from that perspective. Can we find prior art of other profiling tools using a log scale. If so, I'm sold. If not, we should find out why as we aren't the first people to have the problem that we need to fit all the bars on the same screen.

**Comment by InMatrix** [comment]
I'm not aware of using a logarithmic scale in profiling tools, but it seems to be a standard solution for this kind of problem in other domains [1]. Using a log scale in itself is probably fine as long as it's clearly marked so and the user can still hover over each bar and see its actual value. What I'm not sure about is how the switch between the linear scale and the log scare would look like.

[1] https://en.wikipedia.org/wiki/Logarithmic_scale

**Comment by terrylucas** [comment]
If you look at Kenzie screen shot (what it's like today) and my screen shot (I tried out a log scale) there would be a gradual shrinkage, just not as much, when the large bar enters.  The transition isn't great.  This happens today as bars enter the chart the y-axis will adjust and bars may scale too.  I'll create a demo for you to see the transition.

Could we solve the spikes by using category of good, kinda janky, real janky.  We plot frames in that scale then users can hover/click to drill in.  Since the chart is so short its difficult to have much detaill in the chart.

Another possible solution - allow a vertical sizing bar for the chart to grow help alleviate the dramatic flat line and spike more vertical chart space would help.

**Comment by InMatrix** [comment]
I think it's tricky to do the transition right, since a transition can occur when the user is not paying attention to the graph. 

> Could we solve the spikes by using category of good, kinda janky, real janky.

This is an interesting idea. For the initial detection of perf problems, I think that's sufficient. We can condense the graph to a 2 by N grid, and color code the categories representing janky-ness. It will look like a heat map. 

The specific value of each frame's rendering time becomes important when the user made a fix and wanted to observe if that has resulted in any improvement. Categorical information will not be enough. However, I'd argue that the current graph doesn't do this kind of before and after comparison well either, since it's hard to remember the previous value. I had a study participant literally took a screenshot of the old graph and then compare it with the new one. What users need is probably the ability to record user input and then play it back after making some code changes. Then the new graph can be overlaid on top of the old graph.

**Comment by InMatrix** [comment]
Another option is to cap the height but add a "shooting through the roof" effect for those bars taller than the upper bound of the graph. 

![new project](https://user-images.githubusercontent.com/348942/53672879-5518c580-3c39-11e9-8e8a-83d1e071181f.png)

Zoomed in view:
![image](https://user-images.githubusercontent.com/348942/53672906-75e11b00-3c39-11e9-80db-623d029ccb91.png)

**Comment by jacob314** [comment]
Having the bar shoot through the roof seems like the most intuitive option we have. 
@terrylucas what support does plotly have to enable something like this? If there is an existing option for something similar lets try it
