### ISSUE TITLE
DevTools network shows duplicate records

### ISSUE THREAD

**Issue by MRezaKarimi** [flutter/devtools#3607]
I use Dio package to send request to server and the problem is that Network logs each request multiple time.

![Screenshot from 2022-01-29 11-26-13](https://user-images.githubusercontent.com/39339552/151652878-7e3e30df-0df5-4855-9832-97160544aacb.png)

**Comment by dinoudon** [comment]
I also got identical requests record with Dio. 
![image](https://user-images.githubusercontent.com/8967055/167983058-43d95473-9712-4ee4-a21e-9223f860847e.png)

**Comment by Coder7777** [comment]
> 

It's the same for Dio. The flutter devTools is so weak with a lot of bugs. 

Especially for the network panel.

**Comment by Coder7777** [comment]
> This also happens to me, but not with `dio`, with `graphql`.

It's the same for Dio. The flutter devTools is so weak with a lot of bugs.

Especially for the network panel.

**Comment by CoderDake** [comment]
Fixes for the duplicate entries in the Network request list should now be fixed in **Devtools 2.22.1**.
You can try those changes out on the flutter master channel by doing the following:
`flutter channel master; flutter upgrade`

The duplicate entries should then stop occurring :)

So at least for now if you need to do some network debugging the flutter master channel should help enable you a bit, then you can switch back to the channel that you develop on normally :)

Feel free to reach out if you have any questions or concerns

**Comment by CoderDake** [comment]
Fixed in: https://github.com/flutter/devtools/pull/5056
