### ISSUE TITLE
Add functionality to set custom project directories from the Inspector

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#3941]
For customers who launch their app from the command line, we cannot get project directory information from the IDE. Without the correct project directories set, the inspector may not show all the widgets that are part of a user's project.

**Comment by kenzieschmoll** [comment]
We'll want to build this in a way that the project directories a user sets can also be used in debugger (FYI @elliette)

**Comment by kenzieschmoll** [comment]
related https://github.com/flutter/devtools/issues/3919

**Comment by CoderDake** [comment]
With Kenzie's direction i was able to determine that using `WidgetInspectorService.instance.setPubRootDirectories()`
In order to tell devtools about the packages that widgets can be found in.
In my case, I added a widget to `devtools/packages/devtools_shared`.
Then in the main.dart for devtools_app I added the following
```
  final cur = Directory.current.parent.path;
  WidgetInspectorService.instance.setPubRootDirectories([
    "${cur}/devtools_app/",
    "${cur}/devtools_shared/",
  ]);
  ```
  
  After adding that code devtools was then able to find the widgets from the shared app

**Comment by CoderDake** [comment]
Testing in VSCode I was able to make sure that opening devtools through VSCode, the pubrootdirectories get overriden with those that would be set through vscode.

**Comment by kenzieschmoll** [comment]
related https://github.com/flutter/devtools/issues/2721

**Comment by CoderDake** [comment]
Main functionality for this is now in the master branch
