### ISSUE TITLE
`Timeline.instantSync` is not shown in DevTools

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/devtools#3954]
Hi thanks for the framework! I have some `Timeline.instantSync(...)` to report some events, and I also want to see some events reported in other libraries/the flutter framework. However, in DevTools's Performance panel, I cannot see it. I can only see spans created by `Timeline.startSync`.

p.s. redirected from https://github.com/flutter/flutter/issues/101260

**Comment by kenzieschmoll** [comment]
We have a TODO here to support instant events: https://github.com/flutter/devtools/blob/233ba70d1791b868e47fc290f37d30e988c0544e/packages/devtools_app/lib/src/screens/performance/timeline_event_processor.dart#L212-L213

However, since we are investigating other trace viewer solutions, we'll hold off on adding support for this right now.
