### ISSUE TITLE
Widget Inspector does not show code when a widget is selected in Widget Tree

### ISSUE THREAD

**Issue by mkalmajid** [flutter/devtools#4615]
This happened after a recent update to vscode, and possibly flutter as well. A few days ago, when i double clicked a widget in the widget tree, a new file/window is opened that points to the widget's code in its own file. This also works when I choose "Toggle select widget mode" and click on a widget from the simulation on my phone, which also points to the widget code.

How it used to work: 
1. Run and Debug my application
2. Choose Dart DevTools and use Widget Inspector
3. Click on a widget in the Widget Tree
4. A new page is opened pointing to the widget inside the code.

Just to clarify, I have already tried restarting vscode and my device, uninstalling and installing Dart and Flutter plugins, and reinstalling VSCode. Nothing worked unfortunately.

**Comment by CoderDake** [comment]
You can clean the project from VSCode using the `Flutter: Clean Project` action as well

**Comment by mkalmajid** [comment]
I have already done this several times but it did not work unfortunately. I have also tried downgrading VSCode to version 1.70.2, but it's still the same.

**Comment by CoderDake** [comment]
I must have messed up something while testing this yesterday. It looks like I have been able to reproduce this on  `Flutter 3.5.0-8.0.pre.16` but it seems to work on  `Flutter 3.34`.

**Comment by DanTup** [comment]
Sorry for the bother. This is missing functionality in the new SDK debug adapters that I only recently discovered.

Right now, nobody on Stable channels is using the new debug adapters unless they have explicitly opted-in (because there were some other missing features in stable). Everyone on pre-release branches _is_ opted in by default (because I believed we had patched all missing features in master/latest beta).

If you need this functionality, you can explicitly opt-out of the new debug adapters for now by adding the following to your VS Code user settings:

```
"dart.previewSdkDaps": false,
```

There's an issue tracking this at https://github.com/Dart-Code/Dart-Code/issues/4193. The way this functionality was previously implemented is a bit complicated for the client (and causes some issues with users wanting to use `inspect()` themselves in code) so I'd prefer to implement a more specific API for this (and I think @jacob314 has mentioned this before), but I don't yet know how involved that will be.

**Comment by mkalmajid** [comment]
Thank you, this actually fixed the issue. I knew it had something to do with the updates I got but I wasn't sure which one.
