### ISSUE TITLE
Switch DevTools to the VM's protozero based RPCs and include CPU samples in the timeline

### ISSUE THREAD

**Issue by rmacnak-google** [flutter/devtools#4755]
The timeline view should overlay the CPU samples with the explicitly recorded events. Compare Catapult as loaded in Observatory.

**Comment by bkonyi** [comment]
@kenzieschmoll is this something that will be resolved with Perfetto integration?

**Comment by kenzieschmoll** [comment]
Unfortunately, no. Pefetto does not support including cpu samples for the Chrome Trace Format. This would be resolved, though, if we can switch the VM over to the protozero tracing format.

**Comment by rmacnak-google** [comment]
The VM does not provide the CPU samples in Chrome Trace Format.

**Comment by kenzieschmoll** [comment]
How are they passed on to Catapult from Observatory then? I would expect this is how Catapult is reading the data in and marking the samples: https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.yr703knxre9f

**Comment by rmacnak-google** [comment]
The __*VM*__ does not provide the CPU samples in Chrome Trace Format. __*Observatory*__ converts the data to Chrome Trace Format because that's what Capapult wants. All the relevant data is in the VM's response and the client is responsible for the format requirements of whatever viewer it chooses. No VM changes are needed if DevTools chooses Perfetto.

**Comment by kenzieschmoll** [comment]
> All the relevant data is in the VM's response and the client is responsible for the format requirements of whatever viewer it chooses. 

Correct. And we can post up information to Perfetto in the Chrome trace format, just as Observatory posted information to Catapult:
```
{
  "traceEvents: [...],
  "stackFrames: [...],
}
```

The issue with this is that Perfetto does not import stack frames information from .json traces yet. On the Perfetto side, it would be a matter of parsing that json and inserting the stack frame info into the right tables in its trace_proceessor. The Chrome tracing format has a long tail of features, like the stack samples that are not implemented. This is because the Chrome Trace Format is now considered a legacy format, and the Perfetto team has put their cycles towards supporting the preferred protozero format.

> No VM changes are needed if DevTools chooses Perfetto.

We will not get the CPU samples in the Timeline for free by switching to Perfetto (due to the reason above that cpu samples are not supported for the Chrome trace format). We would get this for free by switching to Perfetto _and_  conforming to the protozero format.

**Comment by bkonyi** [comment]
I've done some initial work here to plump the Perfetto proto to the Perfetto instance in DevTools (see https://github.com/flutter/devtools/commit/a8581f1223a85d32dd947cc060805a98cc746a8c). If we only cared about Dart CLI applications, this would basically be the only change needed (although CPU sample events do seem to be missing frame information, which I haven't had a chance to figure out yet).

I spent a bit of time trying to do a full migration of DevTools from the Chrome Trace Event format to the Perfetto proto format, but it looks like it's going to be a deep dive. I unfortunately don't have the cycles to dig into this right now, but it looks like there's going to be a lot of complexity related to the Flutter specific functionality and possibly the import/export feature.

DevTools makes a lot of assumptions based on the structure of the Chrome Trace Event format, many of which are deeply embedded in the logic for handling Flutter frame events. This includes:

- Reaching directly into the backing JSON of TraceEvent to poke at some specific fields, something that isn't possible to do with the Perfetto TrackEvents.

- Reliance on the CTE format's COMPLETE events, which don't exist in the Perfetto format. See: https://perfetto.dev/docs/reference/trace-packet-proto#TrackEvent.Type

- Reliance on the CTE's async begin/end events, which don't exist in the Perfetto format. I _think_ Perfetto treats sync and async events identically, where async events are simply logged to their own track.

These are only the issues I'm aware of; there's probably a lot more that needs to be dealt with as well. I'm not sure what will need to be done to get import/export working as well.
