### ISSUE TITLE
Hint popup windows within Flutter inspector (IntelliJ IDEA 2022.2.1 (Ultimate Edition)) does not auto-hide

### ISSUE THREAD

**Issue by NashidForbes** [flutter/devtools#4935]
Hint popup windows within Flutter inspector (IntelliJ IDEA 2022.2.1 (Ultimate Edition)) does not auto-hide when clicking on another part of the Flutter Inspector window. 

What steps will reproduce the issue?
1. Start up Android Emulator (Run image Pixel 3A API 29)
2. Deploy a any Flutter app to emulator
3. Start up Flutter inspector and click on any icons in the top right corner of the Flutter inspector window.

What is the expected result?
A hint popup mini window will appear and then disappear when you click on any other window in the IDE.

What happens instead?
The hint popup window stays permanently within the Flutter inspector window.

![Screenshot at 2022-11-06 17-08-21](https://user-images.githubusercontent.com/50852214/207181412-eba9bc20-f948-4828-9704-7ce58f18cf08.png)

**Comment by NashidForbes** [comment]
This is for DevTools version 2.15.0

**Comment by CoderDake** [comment]
Hey @NashidForbes I believe this is fixed in Devtools 2.18.0 or 2.19.0
To get access to those you can update your Flutter version to one of the flutter beta releases.
I've posted a comment here with more information.

https://github.com/flutter/devtools/issues/4946#issuecomment-1355147517

Please reach out if you are still having issues after trying those beta releases
