### ISSUE TITLE
After hot restart of app, debugger does not show main.dart

### ISSUE THREAD

**Issue by polina-c** [flutter/devtools#5017]
https://user-images.githubusercontent.com/12115586/211373637-5565d036-def4-4f9e-9f58-5ec203ff2be2.mov

**Comment by polina-c** [comment]
@elliette

**Comment by elliette** [comment]
The debugger panel fetches the code sources from the VM service, so I'm guessing this is a VM service issue, not a debugger panel issue. Adding @bkonyi

**Comment by bkonyi** [comment]
Hot restart kills the isolate and brings up a new isolate. The debugger isn't showing `main.dart` here as it's switching to the next isolate in the isolate selector, which so happens to be the `vm-service` (which doesn't have a `main.dart`).

The fix here is to detect a hot restart event, and then switch to the new root isolate when it spawns.

**Comment by CoderDake** [comment]
I've got a fix up for https://github.com/flutter/devtools/issues/6435
So I'll check if reselecting the main isolate properly helps this use case.

**Comment by CoderDake** [comment]
Looks like there is a flicker to the other isolate's files while the hot restart is happening, but the main.dart file comes back immediately after.

Does that seem like acceptable behaviour for such a situation? @bkonyi @kenzieschmoll 

https://github.com/flutter/devtools/assets/1386322/5e7c9890-b5d2-4962-a855-5ba3495ad311

**Comment by kenzieschmoll** [comment]
How long is the main isolate down? I think it would be reasonable to delay 500ms or similar to see if the main isolate comes back before we switch the the next available isolate.

**Comment by CoderDake** [comment]
@kenzieschmoll it seemed like it was <1s when  I was testing the behaviour. 
I'm It would be easy enough to try something like that with a callback on a timer, but I kind of wonder  if this may just kick the can down the road a bit.
Depending on a lot of factors it could be longer than that which ends up causing the same issue for the user. 
This is the worst kind of behaviour too, since it is akin to a menu changing when you aren't expecting it to change.

This the flicker is unfortunately another issue that we have that would be solved completely if we had a succinct interaction with the hot restart state.
It would be way cleaner to have a "hot restarting" behaviour built into the screens since behaviour isn't well defined in that gap anyways (and might be case by case per situation too)

**Comment by kenzieschmoll** [comment]
> It would be easy enough to try something like that with a callback on a timer, but I kind of wonder if this may just kick the can down the road a bit.

We should have analytics around hot restart time that we can use as a heuristic if we want to cover *most* cases with a delay (as long as this is sub-second, I don't think it would be a great experience otherwise). @jayoung-lee do we have numbers on the average hot restart time?

**Comment by jayoung-lee** [comment]
It looks like `hotEventOverallTimeinMs` (index=13) has the information. https://github.com/flutter/flutter/blob/951653a1c06b3207448f7bc66ba91b52e6a06521/packages/flutter_tools/lib/src/reporting/events.dart#L94C7-L94C48

The median value for restart events yesterday was 1,235 ms (average: 2,602 ms).

**Comment by CoderDake** [comment]
Since the main work here has been complete, marking it as done. 
https://github.com/flutter/devtools/issues/6850 has been opened to reflect the desire for a flickerless behaviour during hot restart.
