### ISSUE TITLE
Flutter Widget Inspector Error in VSCode

### ISSUE THREAD

**Issue by jskpeace** [flutter/devtools#5038]
<-- Please describe your problem here. Be sure to include repro steps. -->
___
**DevTools version**: 2.15.0

In Widget Inspector
Widget Tree
Layout Explorer
![Reference_Execution screen](https://user-images.githubusercontent.com/56624315/212204187-7cc63839-539e-4d66-8bf6-69f22cc59eed.png)

Widget Details Tree

https://flutter.dev/devtools/inspector

No client connection

* I think it's a Flutter Plugin error.
* The new Flutter project menu does not appear in Android studio too.

**Comment by kenzieschmoll** [comment]
@DanTup does this look like something you've recently addressed?

**Comment by DanTup** [comment]
This looks a little similar to #4989, which I believe is a caching issue (after switching from `master` to `stable`, the `master` JS file is still loaded, which doesn't work correctly).

@jskpeace can you try changing the DevTools port in the VS Code User Settings to something like 9200 (the default is 9100) and restarting VS Code to see if that helps?

![image](https://user-images.githubusercontent.com/1078012/212294900-74215718-953e-4590-86fc-c1390804232d.png)

If it does, it's likely the same issue and we need to get to the bottom of why a cached JS version is being served up (#3896 is tracking caching issues).

**Comment by ajanec01** [comment]
Is anything being cached at a project level? I have two projects and I'm using fvm as they're using different flutter versions. I started getting issues in one of them when I accidentally used global flutter installation (not fvm) and I've not managed to get it working since.

Since then I only manage to get the dev tools working in the project with the newer flutter version, for the one that uses the older version the dev tools window only shows "Not found" and when I switch to a different port I'm able to pick a widget inside the simulator but the with
get tree is not showing up.

**Comment by DanTup** [comment]
I don't know of anything that would be cached per-project. I would expect any caching (in the browser or VS Code) to be shared by all projects (for a given port number).

If you're working on multiple projects with different Flutter versions and trying to use the same port number for DevTools in each, then you're likely to hit these issues. You could work around this (until the underlying issue is resolved) by using a different port number for each project (you can set it in the _Workspace_ settings instead of _User_ settings).

**Comment by elliette** [comment]
https://github.com/flutter/devtools/issues/3896 has been fixed, so I'm going to close this as well. Please re-open if this is still occurring.
