### ISSUE TITLE
Network does not show any request made

### ISSUE THREAD

**Issue by Sesa1988** [flutter/devtools#5070]
Hi,

I have basically two issues:

- It never shows any requests made on startup
- It sometimes does not show any requests made after startup, have to do multiple restarts and stop, play until this works

https://user-images.githubusercontent.com/26410357/213454164-e22b722e-4c2d-4108-b115-b1fe671bd123.mov

___
**DevTools version**: 2.15.0
**Connected Device**:
CPU / OS: x64 (64 bit) macos
Dart Version: 2.18.6
Flutter Version: 3.3.10 / stable
Framework / Engine: 135454af32 / 3316dd8728
Connected app type: Flutter native (debug build)

**Comment by CoderDake** [comment]
Hey @Sesa1988 thank you for your ticket! I believe this is an error being caused by an integer overflow, and I've got some fixes moving through the pipes right now that should help out with this.
I'm tracking the fixes over here on this ticket: 
https://github.com/flutter/devtools/issues/2860#issuecomment-1386187130

Once the fixes are through I'll put out a ping on that issue, and then hopefully your issue will be fixed :D
