### ISSUE TITLE
Debugger page fails to auto-open `main.dart` when connected to web app

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#5350]
When DevTools is connected to a web app, the debugger page auto-opens the Flutter bootstrap file, instead of the app's `main.dart` file: 

![Screenshot 2023-03-03 at 10 44 43 AM](https://user-images.githubusercontent.com/21270878/222802514-200321a9-c4f5-4da2-957d-ad939503ef8d.png)

We should make sure the debugger page opens the `main.dart` file instead of this bootstrap file, which is the intended behavior.

However, there is also the question of discoverability of the file search bar. Instead of loading `main.dart`, we could default to showing a page that tells the user how to open a file. See https://github.com/dart-lang/webdev/issues/2010

**Comment by elliette** [comment]
I know why this is happening:

- In DevTools, we open up to whatever the `rootLib` is (as set by the VM service / DWDS): https://github.com/flutter/devtools/blob/f895e1856cbd821bbf586009c02878b360e515e4/packages/devtools_app/lib/src/screens/debugger/debugger_controller.dart#L473
- In DWDS, we set the `rootLib` to be `org-dartlang-app:/web_entrypoint.dart`. The reasoning for this is explained in: https://github.com/dart-lang/sdk/issues/44760. However, I think we intended to change it to `main.dart` in the future, see: https://github.com/dart-lang/sdk/issues/44760#issuecomment-810416777 @annagrin Do you know where that stands? I think this would be our best option.

The other option is to have DevTools try to find the `main.dart` file in the list of scripts, but I don't like that solution and think it should be determined by the VM service / DWDS.

**Comment by annagrin** [comment]
Unfortunately this is tricky - in dwds we set the rootLib of the VM incorrectly to the wrapper of the main since we don't know what is the correct one. One of the solutions we were thinking about is adding build metadata (constructed by the build, or frontend server in this case) to send all kinds of useful information to dwds (including main module, main module to show in the debugger, locations of dill files, compilation flags etc)

For now we can think of hacking it somehow - if we have an easy way to detect the main module in flutter tools, just pass it as a parameter to dwds? But I am not sure if we do.

I think this should be possible - flutter tools creates a bootstrap to start the main wrapper, is we can find what created the wrapper we can find the main:)

Starting point would be:

https://github.com/flutter/flutter/blob/26b6c1bedda2a62bb0ce84cdd7932769d99f1e52/packages/flutter_tools/lib/src/web/bootstrap.dart#L16

**Comment by elliette** [comment]
Note: Also investigated how to sort the scripts shown to the user when they open their file search. Started making changes in https://github.com/dart-lang/webdev/compare/master...elliette:sort-scripts, but I think it will also require DevTools changes.

**Comment by elliette** [comment]
This was fixed in https://github.com/dart-lang/webdev/pull/2047
