### ISSUE TITLE
Library not found errors after hot restart for flutter_web

### ISSUE THREAD

**Issue by jakemac53** [flutter/devtools#554]
Whenever I do a hot restart for flutter web I see in the console a bunch of `Uncaught Instance of 'LibraryNotFound'` errors - they don't seem to affect the functionality of the app though.

**Comment by grouma** [comment]
We check to see if this is a flutter or flutter web app by doing an eval:
https://github.com/flutter/devtools/blob/master/packages/devtools/lib/src/connected_app.dart#L45

This logic works when DevTools is initially loaded. However when we trigger a hot restart, for some reason the LibraryNotFound exception is rethrown and is not caught. We should refactor this code to look at the libraries instead of doing evals we know will fail.
