### ISSUE TITLE
Network

### ISSUE THREAD

**Issue by Rey9530** [flutter/devtools#5601]
The response and the payload of the requests cannot be observed

![Screenshot 2023-04-03 at 11 27 03](https://user-images.githubusercontent.com/56655911/229583239-45978054-546f-497e-9377-e0dc37264deb.png)
![Screenshot 2023-04-03 at 11 27 16](https://user-images.githubusercontent.com/56655911/229583294-afeeecd3-8ef1-4e47-8022-4443ab68a8b0.png)
___
**DevTools version**: 2.20.1
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 2.19.6
Flutter Version: 3.7.9 / stable
Framework / Engine: 62bd79521d / ec975089ac
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
This is likely fixed by recent work on the Network page that is included with DevTools versions 2.22.1 and greater. You can switch to the flutter beta channel to try this version, or even build DevTools from master if you are completely blocked. If you are still seeing this issue on DevTools > 2.22.1 please re-open this issue. Thanks!
