### ISSUE TITLE
How to check "RSS" memory high usage (>1GB)? (Willing to PR)

### ISSUE THREAD

**Issue by fzyzcjy** [flutter/devtools#5869]
Cross-posted from https://github.com/flutter/flutter/issues/128099, since this also seem to be a devtool problem.

**Comment by kenzieschmoll** [comment]
@polina-c

**Comment by polina-c** [comment]
You can beta test leak_tracker aout-snapshotting: https://github.com/dart-lang/leak_tracker/blob/main/doc/USAGE.md.
Or, just periodically check ProcessInfo.currentRss in dart:io.

If dart heap is not growing, but RSS is growing, it is because of external memory usage. I would experiment what events cause the growth.

**Comment by polina-c** [comment]
@bkonyi

**Comment by fzyzcjy** [comment]
@polina-c Thank you! I will try that.

**Comment by fzyzcjy** [comment]
> @polina-c just periodically check ProcessInfo.currentRss in dart:io.

Btw, I am writing my infra for memory testing. Currently I checked https://github.com/flutter/flutter/wiki/How-to-write-a-memory-test-for-Flutter and there are a few ways. I wonder whether `ProcessInfo.currentRss` can be a way of knowing the memory consumed? Then it may not have some cons like "Polling ADB may trigger collections on the Java heap."

**Comment by bkonyi** [comment]
If you call `ProcessInfo.currentRss` in the application that you're seeing high memory usage in, that will give you the RSS of the process.

**Comment by CoderDake** [comment]
Closing since the other issue was already closed.
