### ISSUE TITLE
Add support for Visual Studio (Windows)

### ISSUE THREAD

**Issue by listepo** [flutter/devtools#6068]
There are quite a lot of people who use [Visual Studio](https://visualstudio.microsoft.com/) as their main IDE when working on Windows. It would be nice to have Dart and Flutter support.

**Comment by kenzieschmoll** [comment]
@DanTup have there been discussions in the past about having the VS Code extension support Visual Studio? Or is the VS dart code extension already available for visual studio?

**Comment by DanTup** [comment]
VS Code extensions can't be shared with Visual Studio, so this would need to be its own extension.

Visual Studio does now have LSP (for language features) support so could use the Dart LSP server:

https://learn.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension?view=vs-2022

I tried this out a few years back (out of curiosity of what would be involved in supporting VS) but it was quite incomplete at the time so I didn't get very far.

It seems like DAP (for debugging) is still not available though:

https://learn.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension?view=vs-2022#:~:text=How%20do%20I%20add%20debugger%20support%3F


I suspect once LSP and DAP are fully supported by VS, getting _basic_ support would probably not be a huge amount of work (similar to how some other editors are using Dart LSP+DAPs). However, there's still a lot of functionality in the VS Code extension (things like providing devices via the Flutter daemon, the test runner, etc.) that is not covered by any standard out-of-process protocol so that would all be missing or require work to implement equivalents of.

I don't know how much demand there is for this (or, how many VS users wouldn't be open to using VS Code for this). Maybe this issue could be used to collect 👍 's  and feedback?

@listepo out of interest, have you tried VS Code? I know they're quite different, but what are the main reasons for preferring VS over VS Code?

**Comment by listepo** [comment]
@DanTup Matter of habit. Until there is full support of C#/.Net for Flutter and the possibility of migration, then I think the demand will be very low

**Comment by kenzieschmoll** [comment]
Closing this issue as not planned. DevTools is supported in the editors that are officially supported by Flutter: https://docs.flutter.dev/get-started/editor?tab=vscode
