### ISSUE TITLE
flutter web devtool - provider not work 

### ISSUE THREAD

**Issue by ibelarouci** [flutter/devtools#6103]
the same code work fine in linux platform!!
in pubspec.yml i use the pakage version: provider: ^6.0.3
![image](https://github.com/flutter/devtools/assets/8080006/720d2b2a-877c-4c5e-b6d2-34547d162144)

**Comment by kenzieschmoll** [comment]
@rrousselGit

**Comment by milasantacruz** [comment]
im facing the same issue. First i was using provider: 6.0.5, then i downgrade the package to provider: 5.0.0

System information:

 Flutter (Channel stable, 3.13.0, on Linux Mint 20.3 5.4.0-156-generic, locale es_CL.UTF-8)

**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: Web linux
Dart Version: 3.1.0
Flutter Version: 3.13.0 / stable
Framework / Engine: efbf63d9c6 / 1ac611c64e
Connected app type: Flutter web (debug build)

**Comment by kenzieschmoll** [comment]
Can you please upgrade to the latest Flutter stable? The version of DevTools should be 2.28.4. The provider screen is actually now shipped as a DevTools extension, so if you upgrade to the latest package:provider version, you will be able to access the extension in DevTools. If you are still facing issues once you upgrade both Flutter and package:provider, please file an issue on the Provider repo so that the package authors can investigate the issue in the context of their DevTools extension

**Comment by paramsinghvc** [comment]
Facing the same error. 

**DevTools version**: 2.34.3
**IDE**: VSCode
**Connected Device**:
CPU / OS: Web macos
Connected app type: Flutter web (debug build)
Dart Version: 3.4.0
Flutter Version: 3.22.0 / stable
Framework / Engine: 5dcb86f68f / f6344b75dc

**Comment by paramsinghvc** [comment]
<img width="1057" alt="Screenshot 2024-05-22 at 20 27 07" src="https://github.com/flutter/devtools/assets/4329912/ef488664-0a97-4a93-9dba-e33496bcbd6d">
Here's the screenshot for the provider tab showing error.
One thing I noted is that, it's only throwing error for when I run web and not for ios.

**Comment by kenzieschmoll** [comment]
Ah. This is coming from the package:provider extension. Please file an issue on the provider issue tracker (there is a link for that on this page "Report an issue", which is out of view on this screenshot).
