### ISSUE TITLE
Dev bump workflow should not run when we are not already on a dev version

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#6137]
This PR is an example of the dev bump workflow bot behaving poorly right after a release: https://github.com/flutter/devtools/commit/8ec8a22dadaf2d39cf1dabf50aceed3aec26d5a1.

The correct move would have been to go from 2.26.0 to 2.27.0-dev.0, but the workflow mistakenly changed from 2.26.0 to 2.26.0-dev.0.

**Comment by kenzieschmoll** [comment]
another example of an incorrect bump: https://github.com/flutter/devtools/pull/6142

**Comment by CoderDake** [comment]
@kenzieschmoll The assumption is that this step is done manually as part of the release process.
https://github.com/flutter/devtools/blob/master/tool/RELEASE_INSTRUCTIONS.md#update-to-the-next-version

 This can be quickly done by running the command in the above step. 
 
 I can definitely add a check to make sure that nothing happens when we find ourselves in this case though.

**Comment by kenzieschmoll** [comment]
short circuiting the workflow if we find ourself in that state sgtm
