### ISSUE TITLE
Flutter web integration test times out and flakes

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#6289]
Sometimes the test fails with a timeout message, and sometimes it fails with this failure: https://gist.github.com/kenzieschmoll/69e7f58fa392e90219b02625ca0e259e

**Comment by kenzieschmoll** [comment]
CC @elliette this is the debugger panel test for web

**Comment by CoderDake** [comment]
Able to reproduce locally by changing https://github.com/CoderDake/devtools/blob/0be05d9e7b1a60c8a84969382f6e8b81e6bf48dd/packages/devtools_app/integration_test/test/live_connection/debugger_panel_test.dart#L110 to  1 millisecond:
```dart
  await tester.pumpAndSettle(const Duration(milliseconds: 1));
  ````
  
  I will change this to the long duration. Hopefully we will see less flake by waiting 6 seconds for the call stacks to resolve, rather than just waiting 3 seconds

**Comment by CoderDake** [comment]
Found this issue in the integration_tests for the above PR
https://github.com/flutter/devtools/issues/6294
