### ISSUE TITLE
P1: Display a warning message if an unsupported browser is used.

### ISSUE THREAD

**Issue by jacob314** [flutter/devtools#66]
We depend on IntersectionObserver which is not available in Safari stable.
In general our UI is only tested on Chrome so even for FireFox it is probably safer to remind users that they should probably be opening the page in Chrome.

**Comment by DanTup** [comment]
Windows testing didn't go too well - we might want use simpler inline scripts that don't require loading the Dart code. Brave also isn't caught (because it pretends to be Chrome but we know has issues (#367)) - not sure how well we can detect that when it sounds like it's actively trying to avoid being detectable (because it's low use would make it easier to fingerprint - something it's specifically trying to avoid).

Edge:

![edge](https://user-images.githubusercontent.com/1078012/54819113-d55ba500-4c92-11e9-8634-4a89ec21887e.png)

IE:

![ie](https://user-images.githubusercontent.com/1078012/54819114-d55ba500-4c92-11e9-9c54-02243682b7ab.png)

Brave:

![brave](https://user-images.githubusercontent.com/1078012/54819111-d55ba500-4c92-11e9-8150-6ad974905dfa.png)

**Comment by DanTup** [comment]
Tested again in IE/Edge using the Dart2JS build, but not a huge amount changed:

![ie](https://user-images.githubusercontent.com/1078012/54846769-8898be00-4cd4-11e9-8417-3d1b473a18dc.png)

![edge](https://user-images.githubusercontent.com/1078012/54846775-8c2c4500-4cd4-11e9-8881-bdb7439a1a9c.png)

**Comment by jacob314** [comment]
Looks like Dart doesn't support these platforms well enough so we have to unfortunately perform this capability detection in JS.

**Comment by DanTup** [comment]
My understanding was that Edge was supported, but I don't know if it's possible to still use APIs that aren't available. If we want to handle IE (I'm not sure if we do, I was just testing for completeness) we probably would need JS though.

Shout if you want me to pick this up next week (sounds like I may have easiest access to Windows).

**Comment by kenzieschmoll** [comment]
Quick update on this - I'm blocked by setting up my Windows machine. I requested an exception so I could download and install external software, and in doing so, I was told the machine needs to be re-imaged with Vanilla Windows so it has no tie to corp. Hopefully this will get squared away within the next couple business days, and then I'll be able to take a look at the Microsoft Edge case next week.

**Comment by DanTup** [comment]
I do have easy access to Windows, so if you have any issues getting it sorted, let me know and I can take a look.

**Comment by kenzieschmoll** [comment]
Hey Danny. I'm having some trouble setting my windows machine up. I may have to wait for something to be mailed to me, so that will be at least a couple days until I can start the setup. If you have some extra time and want to look at this, feel free to do so. Happy to help in any way I can! Thanks.
