### ISSUE TITLE
Filtering vs searching is confusing

### ISSUE THREAD

**Issue by CoderDake** [flutter/devtools#6798]

**Comment by kenzieschmoll** [comment]
Persisting filters is tracked by https://github.com/flutter/devtools/issues/6800, editing this title to reflect the issue this tracks. We could at the very least document the different between search and filter or add a note to the filter dialog that makes it clear that logs matching the filter query will be hidden.

We could also polish the filter dialog to be more sophisticated and dynamic. (e.g. giving the user a list of log tags they could filter by based on the actual content of the logs instead of just having a string query they have to build).

**Comment by kenzieschmoll** [comment]
This is fixed by https://github.com/flutter/devtools/pull/8427
