### ISSUE TITLE
DevTools fails to load embedded in VS Code on some machines

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#6835]
This was raised at https://github.com/Dart-Code/Dart-Code/issues/4855. DevTools is failing to render when hosting inside VS Code for @lukehutch. It looks like this:

![image](https://github.com/flutter/devtools/assets/1078012/c82d3499-0ffa-4d6e-9775-87623f0131c8)

And the console is full of errors like this:

![image](https://github.com/flutter/devtools/assets/1078012/41e11410-f067-4afb-ac1a-4593aba909b3)

It's the latest VS Code and Flutter on Linux. It's not clear how widespread this issue is (I suspect if it was common it would have come up before, however Luke mentioned it only started recently so it could also have begin with a recent VS Code, Flutter or other update).

I've posted some additional steps for Luke to try at https://github.com/Dart-Code/Dart-Code/issues/4855#issuecomment-1827756257 (to rule out it being specific to DevTools), however @jacob314 suggests that we should do some work here such as:

- Ensure these kinds of failures can be reported to analytics so it's easier to tell how widespread the issue is (and perhaps if it's restricted to Linux, etc.)
- Notice that the error is occurring and replace the page with some kind of message explaining the issue, with a link that re-opens DevTools externally (eg. by postMessaging the usual `launcUrlVsCode()` implementation)
  - perhaps an API for DevTools to show notifications in VS Code would make sense via DTD in future

**Comment by jacob314** [comment]
Some background info:
We used to offer a fallback to the html backend after detecting multiple errors from canvaskit taking the extreme step of showing a modal dialog because some of the issues were bad enough that the browser would hang if we didn't pause the page.
Context:
https://github.com/flutter/flutter/issues/72727
At this point I think the canvaskit backend is generally stable enough and the performance delta between canvaskit and the html backend is large enough that we don't want to bring back the fallback to the html backend. Additionally, we would have to integrate the fallback with devtools extensions make it a lot of work for something that may not impact many users. I agree with the two steps Danny wrote of tracking this via analytics so we can figure out how large the issue is and showing a vscode native notification that can be clicked on to open devtools in a browser to mitigate the issue for the hopefully small number of users impacted.

Historically our code to fallback to the web backend had some false positives so risked annoying a few users whose DevTools were still running well.

**Comment by lukehutch** [comment]
I upgraded Fedora to the latest version (version 39, x86_64), made sure the NVIDIA driver was updated to the latest version (version 545.29.02), and rebooted (since I was wondering if the GPU driver wasn't being reconfigured properly on suspend/resume, which I do every night). There is no change in behavior on a fresh reboot, with these updates.

I'm wondering if this is actually a bug in CanvasKit, because the message `Program binary could not be loaded. Binary is not compatible with current driver/hardware combination. Driver build date Oct 26 2023. Please check build information of source that generated the binary` seems to indicate that CanvasKit is simply refusing to compile the shaders due to a version mismatch, even though the compilation is likely to actually work.

I searched the Chromium and CanvasKit source for the error message "Binary is not compatible with current driver/hardware combination", and could not find it.

The most relevant thing I could find is this issue in Electron:

https://github.com/electron/electron/pull/40467

This will be out in Electron v27.0.4. The current version in VS Code's `package.json` is v25.9.2.

What's the likely timeline for a bump to at least v27.0.4 of the Electron dep, so that I can test this?

**Comment by lukehutch** [comment]
It looks like this is the same as this downstream bug in VS Code: https://github.com/microsoft/vscode/issues/190437
Fixed by https://github.com/electron/electron/pull/40450
Backported to https://github.com/electron/electron/pull/40467

**Comment by DanTup** [comment]
@lukehutch if it's the same issue, it looks like that fix was back-ported into Electron v25.9.4 which [according to the bot](https://github.com/microsoft/vscode/issues/190437#issuecomment-1811853147) is now in the Insiders build of VS Code. If you're able to try that out (it can run side-by-side with stable) it'd be interesting to know if the issue goes away.

**Comment by lukehutch** [comment]
@DanTup Confirmed, this is fixed with the Insiders build!

**Comment by Aturex1** [comment]
Same here too, I'm also using the newest fedora version. However, I have AMD-RADEON graphics and not NVIDIA. It doesn't load the DevTools in VSCodium, but works on web and VSCodium Insiders.

**Comment by DanTup** [comment]
If it's working in Insiders but not stable, I suspect they just haven't shipped it yet. The last VS Code release was in December and probably was branched prior to the fix noted above.

**Comment by DanTup** [comment]
Based on comments above and at https://github.com/Dart-Code/Dart-Code/issues/4855#issuecomment-1959779848 I think this issue has been fixed in a recent Code release. If you're still seeing this on the latest stable (1.86) VS Code, please post details (including details of your OS/graphics card) and we can re-open this.
