### ISSUE TITLE
Following recommendation to add const causes build failure

### ISSUE THREAD

**Issue by kalafut** [flutter/devtools#6891]
Dev Tools version: 3.78.0

Given this code:
```dart
class Example extends StatelessWidget {
  final size = 30.0;

  Example({super.key});

  @override
  Widget build(BuildContext context) {
    return Text(
      "Hello",
      style: TextStyle(
        fontSize: size,
      ),
    );
  }
}
```

I'm getting recommendations first to make `Example` const, and then `Text` and `TextStyle`. But when I accept those mods, I get a build failure: 

```
lib/screens/scoreboard/controller_bar.dart:265:18: Error: Constant evaluation error:
    return const Text(
                 ^
lib/screens/scoreboard/controller_bar.dart:268:19: Context: Not a constant expression.
        fontSize: size,
```

It's also worth noting that if I add the `const` changes, I do not get red inline build errors, but only the above compile-time errors.

**Comment by parlough** [comment]
Making the `Example` constructor `const` is fine, but the other cases are due to https://github.com/dart-lang/sdk/issues/53927, which resulted in the analyzer thinking the `final` field of a class with a `const` constructor are is in a constant context.

I've opened a cherry-pick request to bring the corresponding fix to the stable channel: https://github.com/dart-lang/sdk/issues/54232.

In the mean time, you can ignore the `prefer_const_constructors` lint on those lines or make the `size` field actually `const`.

I'm going to close this in favor of the original issue and the cherry-pick request, but thanks for opening an issue!

**Comment by kalafut** [comment]
Thanks for the prompt reply and cherry pick.
