### ISSUE TITLE
DevTools makes lots of requests for release notes that are 404s

### ISSUE THREAD

**Issue by DanTup** [flutter/devtools#7114]
When I have the network tools open I see DevTools make a lot of requests for release notes that are 404s:

![image](https://github.com/flutter/devtools/assets/1078012/4e75b9a6-cbbd-4a60-8957-81adff4107e9)

I thought this might have been known and just how this works, but @jacob314 was surprised by it and suggested I file an issue.

**Comment by parlough** [comment]
Without looking at the code, I'm assuming it keeps looking until it finds the most recent release notes on the website, since not all versions have one or at least not right away. Stable versions usually have a corresponding entry, so I imagine it doesn't happen too much for developers on stable.

If it's helpful, the site build could generate(and host) a file with information about what release notes are available?

**Comment by kenzieschmoll** [comment]
> If it's helpful, maybe the site build could generate(and host) a file with information about what release notes are available?

This would be helpful. Then DevTools could just request this file and do the logic on our side to find the most recent version of release notes to show instead of relying on http requests in a try catch to perform this logic.
