### ISSUE TITLE
Layout explorer is not dense enough for IDE

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#7758]
This view is difficult to use when embedded in the IDE. This should be modified so that the UI is far more dense. Arbitrarily, this view should work well in when it is ~2-3" wide and tall.

This should be part of the work for inspector V2 to provide a great embedded IDE experience.

**Comment by elliette** [comment]
Keeping track of https://github.com/flutter/devtools/pull/8161#issuecomment-2274140091 here

**Comment by elliette** [comment]
Some notes here:

Currently, for the following code snippet:

```
Padding(
        padding: EdgeInsetsDirectional.only(start: appBarPadding),
        child: IconButton(
          key: const ValueKey('Back'),
          icon: const BackButtonIcon(),
          tooltip: MaterialLocalizations.of(context).backButtonTooltip,
          onPressed: () {
            Navigator.maybePop(context);
          },
        ),
      )
```

Which corresponds to this portion of the Widget Tree:
<img width="303" alt="Screenshot 2024-08-08 at 3 10 54 PM" src="https://github.com/user-attachments/assets/5a0277bb-b763-4f1a-ade4-f86cc3d2c148">

In the layout explorer, we show the following:

For the IconButton:
<img width="420" alt="Screenshot 2024-08-08 at 3 15 38 PM" src="https://github.com/user-attachments/assets/6bed393d-ae23-4c9d-81e6-d3a93f3bccfa">

For the Padding:

<img width="418" alt="Screenshot 2024-08-08 at 3 15 52 PM" src="https://github.com/user-attachments/assets/b72e1b9a-aabe-4d6f-b05f-a440c9ac2cb9">

IMO, I don't think the layout we are showing for padding is very useful. I don't particularly care about seeing the ConstrainedBox, particularly because it is the exact same size as my padding (although the layout explorer is a bit misleading in this regard). What I'm really interested is not its parent widget, but its child widget (the IconButton). I would rather see the same view for both of them. 

Something like:

<img width="480" alt="Screenshot 2024-08-08 at 3 38 44 PM" src="https://github.com/user-attachments/assets/aac06c57-fca2-4be7-a0a1-eb0b37cfe4b9">

**Comment by elliette** [comment]
Note: it's unnecessary to show the width / height twice:

<img width="165" alt="Screenshot 2024-08-08 at 3 57 35 PM" src="https://github.com/user-attachments/assets/629d214d-0c49-4c3a-a3a9-760079106d30">
