### ISSUE TITLE
Memory/Network Page in blank (DevTools)

### ISSUE THREAD

**Issue by JeffreyPSA** [flutter/devtools#7879]
When I try to load the memory page or network page from vs code I just get a blank page as shown below:
![image](https://github.com/flutter/devtools/assets/114021588/4b43e601-2a3c-4830-92d0-77a8f27d7a3e)
Also if I try to load the devtools from my web browser (Chrome), the performance tab only shows me this info below
![image](https://github.com/flutter/devtools/assets/114021588/94b65d31-729e-49e3-8045-6864adb5e887)
This is a web app and I'm trying running it in debug mode.
My flutter version is 3.22.1 devtools version is 2.34.3

I need critically check what's going on with the memory performance of this app, but devtools is not working as an shown.

**Comment by kenzieschmoll** [comment]
For Flutter web apps, the following tools are supported by Dart DevTools: Inspector, Logging, and Debugger. For all other needs like Performance, Network, or Memory, you should use Chrome DevTools from the Chrome window your web app is running in.

It looks like we are not properly disabling the DevTools screens that are not supported for web from VS code, which is causing some confusion. @DanTup 

CC @helin24 since we will need to use the `hide=`  param in the IntelliJ tool window URI to hide the unsupported DevTools screens when connected to a web app.

**Comment by DanTup** [comment]
> It looks like we are not properly disabling the DevTools screens that are not supported for web from VS code, which is causing some confusion. @DanTup

We don't have a great way in VS Code to know all the conditions in which we should enable/disable pages (because users can specify their own flags in a run configuration that could target different devices, modes, etc. or use custom launch scripts). I assume these conditions could (in the future) change between SDK versions.

The most reliable thing may be to have some kind of API (via the server, or a service extension, or DTD) that would allow us to determine which pages are available. Although, in the past I thought DevTools showed a message like "this page isn't available for x" that doesn't appear to be working here - would fixing that be good enough so it's at least clear (in some ways, this might be better than just hiding all of the commands, because a use might wonder why they can't find the command to launch a given page).


> CC @helin24 since we will need to use the hide= param in the IntelliJ tool window URI to hide the unsupported DevTools screens when connected to a web app.

Doesn't DevTools already hide the tabs that aren't supported? `hide=` was originally intended only to hide things that otherwise would be supported (for ex. Debugger). VS Code doesn't use `hide=` for anything else and expected DevTools to only show what's available.

**Comment by helin24** [comment]
@DanTup I believe in VS Code we show all of the windows separately, right? vs in IntelliJ we're planning to show an embedded browser that features multiple DevTools tabs (e.g. performance, networking, etc. but excluding inspector and extensions). So I think perhaps the `hide=` param won't be applicable for VS Code.

**Comment by JeffreyPSA** [comment]
@helin24 @DanTup @kenzieschmoll to contribute your fixes, I had been able to see the Memory page using the ctrl + shift + "P" as shown below
![image](https://github.com/flutter/devtools/assets/114021588/df3d5ef7-d033-4996-a6a0-390fc8d3047c)

**Comment by DanTup** [comment]
> @DanTup I believe in VS Code we show all of the windows separately, right?

Yup!


> in IntelliJ we're planning to show an embedded browser that features multiple DevTools tabs (e.g. performance, networking, etc. but excluding inspector and extensions).

I see - but doesn't DevTools already support hiding sections that aren't available based on the app it's connected to? Why would they need to be passed on the querystring? (IMO it'd be better to avoid the IDE needing to have hard-coded rules about what pages are available in what situations if they may change over time, or in the case of VS Code, where use config of wrapper scripts might make it hard to know the kind of device we're running on).

@JeffreyPSA 

> I had been able to see the Memory page using the ctrl + shift + "P" as shown below

Thanks for confirming. This is the location where I'm not sure about hiding it. If you're used to using the memory page for non-web and don't realise it's unavailable for web, it could be more confusing to hide it from this list than the allow you to select it and then show a message saying "The memory page is not currently available when running on web devices" 🤔

**Comment by JeffreyPSA** [comment]
Will you enable Flutter DevTools for web applications in the future? @DanTup @kenzieschmoll

**Comment by kenzieschmoll** [comment]
> Will you enable Flutter DevTools for web applications in the future?

For cases where Chrome DevTools already has developer tooling (like memory, network profiling, etc.) we do not have plans to re-implement this tooling in Flutter DevTools. This is because there is not much value to add beyond what Chrome already provides. For Flutter specific tools that we provide or tools that are low cost to maintain and already work for web apps, these will continue to be supported in Dart & Flutter DevTools (e.g. Inspector, Logging, etc.).

I have pushed up a PR to help with the messaging when certain pages are not supported for the current platform: https://github.com/flutter/devtools/pull/7958
