### ISSUE TITLE
DevTools server instance_reuse_test is timing out 

### ISSUE THREAD

**Issue by elliette** [flutter/devtools#8008]
The  devtools_server `instance_reuse_test` has begun timing out after the most recent DevTools rev into the SDK: https://github.com/dart-lang/sdk/commit/b792a0c914a4bf59d4519fb4e5247b8ca6f9aca7

- This is the test case that is timing out: https://github.com/dart-lang/sdk/blob/e5999393c91c0984fd608a0defcce78e65db3856/pkg/dds/test/devtools_server/instance_reuse_test.dart#L150
- Specifically this `await`: https://github.com/dart-lang/sdk/blob/e5999393c91c0984fd608a0defcce78e65db3856/pkg/dds/test/devtools_server/instance_reuse_test.dart#L186-L187

Looking at what it is testing (whether a launch devtools request can take over an existing disconnected devtools instance), I'm guessing the reason for this regression is the same reason that caused the regression fixed in https://github.com/flutter/devtools/pull/7992

I don't think we need to revert the DevTools release, but the fix might need to be cherry-picked into the SDK. 

FYI @kenzieschmoll

**Comment by elliette** [comment]
Looks like this test was initially added in https://github.com/flutter/devtools/pull/987

I'm trying to figure out what would trigger this scenario (a "launch DevTools" request taking over a disconnected DevTools instance). @DanTup do you have any context here? Thanks!

**Comment by DanTup** [comment]
> I'm trying to figure out what would trigger this scenario (a "launch DevTools" request taking over a disconnected DevTools instance)

The use case here was to support re-connecting an existing DevTools instance that has become disconnected to a new debug session rather than spawning a new one (this was done before we were embedded, where VS Code asks the DevTools server to launch DevTools in the browser, and we don't want to keep spawning new windows if the user keeps stopping and starting debug sessions).

Not at PC atm, but I'll see if I can repro and debug shortly.

**Comment by DanTup** [comment]
The issues seems to be related to the lifetime of the `Initializer`. The handler that handles this message to reconnect to a new VM Service is wired up here:

https://github.com/flutter/devtools/blob/70375f6c6d81faa8f3069aa6dcf2a98c69445455/packages/devtools_app/lib/src/framework/initializer.dart#L54-L56

It's set to auto-dispose, and when I terminate by debug session so that DevTools disconnects, I see that the `dispose` method for `_InitializerState` is running (so presumably it's disposing that subscription to the events from the server). The event to reconnect does come through from the server later and is sent on that stream, but nobody is listening to it anymore.

![image](https://github.com/flutter/devtools/assets/1078012/30e5a59c-68a0-4563-9beb-b39dad2b0507)

It's not clear to me what the lifetime of `Initializer` should be now, but if it's only intended to be live when there is a connection to an app, then probably the handling of this reconnect event should be somewhere higher up (where the subscription can persist even when DevTools disconnects from a VM Service). If the Initializer is intended to still be around, then I guess the question is why is it being disposed.

I had a quick look at where `Intializer` is being used and found this:

```
return paramsContainVmServiceUri
        ? Initializer(builder: (_) => scaffoldBuilder())
        : scaffoldBuilder();
```

So I guess this explains why it's being disposed - during disconnect, the old VM Service URI is removed from the URL/params. What's not clear to me is why this only started failing recently though.

**Comment by DanTup** [comment]
> What's not clear to me is why this only started failing recently though.

Possibly this (added in #7992) is what causes there to be no VM Service URI in the params, and maybe before this change we still had the old one in the URI?

https://github.com/flutter/devtools/blob/70375f6c6d81faa8f3069aa6dcf2a98c69445455/packages/devtools_app/lib/src/framework/disconnect_observer.dart#L58-L64

**Comment by elliette** [comment]
Thank you! 

What I've figured out so far:

- the `Initializer` listens for the new VM connect event: https://github.com/flutter/devtools/blob/70375f6c6d81faa8f3069aa6dcf2a98c69445455/packages/devtools_app/lib/src/framework/initializer.dart#L55
- however, it gets `disposed` on disconnect, so once devtools is disconnected it won't register any new vm service connection events

Working on a fix, not sure I'll have it ready by the release cut off but it can be done as a cherry pick.
