### ISSUE TITLE
Migrate DevTools to use pub workspaces

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#8211]
This will be a good way for us to dogfood the pub workspaces feature and find any devexp / devtools related bugs (like DevTools extensions or IDE integrations).

The workspace `pubspec.yaml` should likely live at the root of `devtools/packages`.

**Comment by kenzieschmoll** [comment]
I pushed up a draft for this at https://github.com/flutter/devtools/pull/8549, but something does not seem to working properly. I followed instructions and examples as closely as possible, but I'm not quite sure what is going wrong. 

Running `dart pub get` from the top-level `devtools/` directory succeeds, but the Problems view in VS code shows 54k+ problems. I have tried restarting the analysis server and the IDE, but I still have analysis issues all over my project. I am opening the root `devtools/` directory in VS Code.

Also, here is the output from running `dart pub workspace list`:
```
Package              Path                           
_                    ./                             
devtools_app         packages/devtools_app/         
devtools_app_shared  packages/devtools_app_shared/  
devtools_extensions  packages/devtools_extensions/  
devtools_shared      packages/devtools_shared/      
devtools_test        packages/devtools_test/        
devtools_tool        tool/   
```

CC @sigurdm - any ideas? Also CC @DanTup in case there could be something going wrong with my local VS Code configuration.

**Comment by sigurdm** [comment]
I believe I found the issue.

On the main branch you have a `packages/pubspec.yaml` file, (which results in a corresponding `packages/.dart_tool/package_config.json`.

On the PR branch there is no `packages/pubspec.yaml`, but when the branch is switched `packages/.dart_tool/package_config.json` remains, because it is .gitignored.

This file is the cause of all the trouble, because the analyzer picks that one up when it traverses directories towards the root.

`pub get` will remove existing `.dart_tool/package_config.json` in any workspace project folder, but not in the interim folders.

The workaround is to run `rm packages/.dart_tool/package_config.json` from the repository root.

We should probably update pub to delete `.dart_tool/package_config.json` from all interim folders in the workspace.
@jonasfj WDYT?

**Comment by kenzieschmoll** [comment]
@sigurdm thanks for looking into this. That fixed my local setup and I think the fix you pushed up to prevent other users from hitting this will be great.

The next issue I am hitting is with `build_runner`. We generate mocks as part of our CI setup, and this is now failing with the move to use workspaces:
```
Running build_runner build for devtools_app...
/home/runner/work/devtools/devtools/packages/devtools_app > /home/runner/work/devtools/devtools/tool/flutter-sdk/bin/flutter pub run build_runner build --delete-conflicting-outputs
Package "build_runner" is not an immediate dependency.
Cannot run executables in transitive dependencies.
Failed to update packages.
ProcessException: Failed with exit code: 65. 
  Command: /home/runner/work/devtools/devtools/tool/flutter-sdk/bin/flutter pub run build_runner build --delete-conflicting-outputs
```

`build_runner` is still listed as a dependency in `devtools_app/pubspec.yaml` but it appears that the system thinks that it is a "transitive dependency".

**Comment by kenzieschmoll** [comment]
Nevermind I got this passing by adding the build_runner dep to the top level pubspec.yaml file.
