### ISSUE TITLE
Logging bar increases event count when toggling settings

### ISSUE THREAD

**Issue by FMorschel** [flutter/devtools#8281]
When settings toggle to show/hide structured errors it increases the event count by one.

https://github.com/user-attachments/assets/cc22ea7e-92a2-44cf-86a3-a7e248d47c63

**Comment by kenzieschmoll** [comment]
This is WAI. When this setting is changed, a service extension is called, which triggers a log event to be fired tracking the service extension state change. There are default filters set to filter out log noise (see the filter button in the top right that is colored blue), so that's why you aren't seeing the log come up. If you had the filters off, this is what the log would look like:

![Screenshot 2024-08-30 at 9 59 47 AM](https://github.com/user-attachments/assets/10e9b4b2-cc1a-4830-8c89-d1c2d23b63aa)

**Comment by FMorschel** [comment]
Ohh, I see. Thanks for the explanation!
