### ISSUE TITLE
Preserve Inspector details tab between when selecting widgets

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#8400]
If I am on the Render Objects tab, for example, and I am switching between selected widgets in the tree, the Render Objects tab should stay selected

**Comment by elliette** [comment]
Hmm I think this is in part because the render objects tab (and flex explorer tab) don't exist for every widget, so we default to always showing the layout explorer tab first. 

We could switch to trying to preserve the current selected tab, and if it doesn't exist switching to the layout explorer tab.

**Comment by kenzieschmoll** [comment]
Could we try storing the preferred tab key / index, and then if that tab doesn't exist, show the first that does?
