### ISSUE TITLE
`generate-code` command generates code with errors

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#8440]
This doesn't appear to be happening on the CI, because tests pass there. But locally, I see these improperly generated mocks each time I run `dt generate-code`.

![Screenshot 2024-10-15 at 2 08 22 PM](https://github.com/user-attachments/assets/eed888ab-e361-4a28-aca9-f947574bc985)

CC @DanTup because I think you've run into this before?
CC @srawlins in case you have any ideas about our [generate mocks setup](https://github.com/flutter/devtools/blob/master/packages/devtools_test/lib/src/mocks/generated.dart/#L12).

Repro steps:
1. Run `dt update-flutter-sdk --update-on-path` to ensure that the `tool/flutter-sdk` directory and your local flutter sdk are on the flutter version that DevTools is pinned to use.
2. Run `dt generate-code` to generate mocks. Optionally, you can also try `dt generate-code --upgrade` to upgrade pub dependencies before generating code. Both resulted in generated code with errors for me.

**Comment by DanTup** [comment]
I've seen this a few times before and it's fairly sporadic. I thought it was just me so I didn't dig into it too much (honestly, I didn't know where to start debugging). Sometimes I just manually fix the file up (changing `dynamic` to the type it wants), but if it's not just me it would be nice to track down.

I just pulled latest (7a9b23fa6) and ran `dt update-flutter-sdk` then `dt generate-code` and did not have this issue. So I tried with `--upgrade` but it still didn't occur.

It's weird because when it happens, it's only for a couple of requests, and as far as I can tell the missing types (which have been replaced by `dynamic`) are all in the same library as other types that were included correctly!?
