### ISSUE TITLE
Display issues with source code

### ISSUE THREAD

**Issue by grouma** [flutter/devtools#905]
The latest version of `DevTools` has some display errors with the source code. 

The source code pane always starts collapsed (this is a regression):
![Screenshot from 2019-08-09 12-57-31](https://user-images.githubusercontent.com/1840773/62805574-44506380-baa5-11e9-92aa-13487bf8ec2d.png)

If a user slides down the divider to display the source code only a subset of the code is displayed:
![Screenshot from 2019-08-09 12-58-21](https://user-images.githubusercontent.com/1840773/62805620-60540500-baa5-11e9-9a53-b16abcc22a09.png)

Scrolling in the source code window will display the rest of the code:
![Screenshot from 2019-08-09 12-58-53](https://user-images.githubusercontent.com/1840773/62805654-72ce3e80-baa5-11e9-8e8a-7792e6b63a95.png)

**Comment by devoncarew** [comment]
Possibly related to https://github.com/flutter/devtools/issues/880.

**Comment by devoncarew** [comment]
It'd be useful to bisect this.

**Comment by devoncarew** [comment]
A bisect didn't work here, so perhaps an issue not related to our commits? A layout issue in Chrome perhaps?

**Comment by kenzieschmoll** [comment]
Two problems here:
1) it is definitely related to #880, or at least this issue bug is magnified by the splitter bug
2) the real problem here seems that codemirror isn't re-rendering on container resize like it is on scroll. One idea would be to add an observer and trigger a rebuild on container resize, similar to what we do for flame charts.

**Comment by devoncarew** [comment]
I think I must have bisected incorrectly; https://github.com/flutter/devtools/pull/913 should fix this.
