### ISSUE TITLE
DevTools doesn't update for window.devicePixelRatio changes

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#995]
If you open devtools on a low dpi monitor, and then drag it to a high dpi monitor, canvas drawings and icons will look a little blurry.

We should find someway to notify DevTools when the value of `window.devicePixelRatio` changes.

**Comment by mdebbar** [comment]
The same issue used to occur when you zoom in/out because that also changes the dpi. We fixed that by listening to `resize` events. Could you check if moving the window to another monitor triggers a `resize` event or not?

/cc @yjbanov in case the latest layer changes made canvas reuse ignore previous canvas's dpi.

**Comment by kenzieschmoll** [comment]
Moving the window across monitors does not trigger a resize event. I checked by adding `window.onResize.listen((_) => print('resize'));`, which does print resize when I actually change the size of the browser window.

**Comment by mdebbar** [comment]
Ok, so that's the problem. There's no way (that I know of) for us to listen to dpi changes when the user moves the window from one monitor to the other. Also, potentially, if the user changes their monitor's dpi/resolution settings.

If there are some tricks to achieve this, I'm all ears :)

**Comment by jacob314** [comment]
Closing as this isn't relevant in the package:flutter version of devtools.
